// Code generated by genstubs. DO NOT EDIT.

package api

import "context"

// NotImplemented (strict) beantwortet jede Operation mit ErrNotImplemented.
type NotImplemented struct{}

var _ StrictServerInterface = NotImplemented{}

func (NotImplemented) AcceptInvitation(context.Context, AcceptInvitationRequestObject) (AcceptInvitationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AddVehicleImage(context.Context, AddVehicleImageRequestObject) (AddVehicleImageResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AdminGetSettings(context.Context, AdminGetSettingsRequestObject) (AdminGetSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AdminListAccounts(context.Context, AdminListAccountsRequestObject) (AdminListAccountsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AdminListFailedJobs(context.Context, AdminListFailedJobsRequestObject) (AdminListFailedJobsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AdminRetryJob(context.Context, AdminRetryJobRequestObject) (AdminRetryJobResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AdminUpdateAccount(context.Context, AdminUpdateAccountRequestObject) (AdminUpdateAccountResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) AdminUpdateSettings(context.Context, AdminUpdateSettingsRequestObject) (AdminUpdateSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CancelTrip(context.Context, CancelTripRequestObject) (CancelTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ChangeMemberRole(context.Context, ChangeMemberRoleRequestObject) (ChangeMemberRoleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ChangePassword(context.Context, ChangePasswordRequestObject) (ChangePasswordResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ChangeVehicleStatus(context.Context, ChangeVehicleStatusRequestObject) (ChangeVehicleStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CompleteOidcLogin(context.Context, CompleteOidcLoginRequestObject) (CompleteOidcLoginResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ConfirmCostOccurrence(context.Context, ConfirmCostOccurrenceRequestObject) (ConfirmCostOccurrenceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ConfirmPasswordReset(context.Context, ConfirmPasswordResetRequestObject) (ConfirmPasswordResetResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ConfirmProposal(context.Context, ConfirmProposalRequestObject) (ConfirmProposalResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CorrectOdometerReading(context.Context, CorrectOdometerReadingRequestObject) (CorrectOdometerReadingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CorrectTrip(context.Context, CorrectTripRequestObject) (CorrectTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateApiToken(context.Context, CreateApiTokenRequestObject) (CreateApiTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateAttachment(context.Context, CreateAttachmentRequestObject) (CreateAttachmentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateCompletion(context.Context, CreateCompletionRequestObject) (CreateCompletionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateConversation(context.Context, CreateConversationRequestObject) (CreateConversationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateCostEntry(context.Context, CreateCostEntryRequestObject) (CreateCostEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateCostPlan(context.Context, CreateCostPlanRequestObject) (CreateCostPlanResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateDocument(context.Context, CreateDocumentRequestObject) (CreateDocumentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateFuelFill(context.Context, CreateFuelFillRequestObject) (CreateFuelFillResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateImport(context.Context, CreateImportRequestObject) (CreateImportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateInvitation(context.Context, CreateInvitationRequestObject) (CreateInvitationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateMaintenanceItem(context.Context, CreateMaintenanceItemRequestObject) (CreateMaintenanceItemResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateNote(context.Context, CreateNoteRequestObject) (CreateNoteResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateOdometerReading(context.Context, CreateOdometerReadingRequestObject) (CreateOdometerReadingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateOdometerSegment(context.Context, CreateOdometerSegmentRequestObject) (CreateOdometerSegmentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateOilEntry(context.Context, CreateOilEntryRequestObject) (CreateOilEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreatePushEndpoint(context.Context, CreatePushEndpointRequestObject) (CreatePushEndpointResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateServiceEntry(context.Context, CreateServiceEntryRequestObject) (CreateServiceEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateTrip(context.Context, CreateTripRequestObject) (CreateTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateTripCategory(context.Context, CreateTripCategoryRequestObject) (CreateTripCategoryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateVehicle(context.Context, CreateVehicleRequestObject) (CreateVehicleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) CreateWebhook(context.Context, CreateWebhookRequestObject) (CreateWebhookResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeclineInvitation(context.Context, DeclineInvitationRequestObject) (DeclineInvitationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteAttachment(context.Context, DeleteAttachmentRequestObject) (DeleteAttachmentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteCompletion(context.Context, DeleteCompletionRequestObject) (DeleteCompletionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteConversation(context.Context, DeleteConversationRequestObject) (DeleteConversationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteCostEntry(context.Context, DeleteCostEntryRequestObject) (DeleteCostEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteCostPlan(context.Context, DeleteCostPlanRequestObject) (DeleteCostPlanResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteDocument(context.Context, DeleteDocumentRequestObject) (DeleteDocumentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteFile(context.Context, DeleteFileRequestObject) (DeleteFileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteFuelFill(context.Context, DeleteFuelFillRequestObject) (DeleteFuelFillResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteImport(context.Context, DeleteImportRequestObject) (DeleteImportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteMaintenanceItem(context.Context, DeleteMaintenanceItemRequestObject) (DeleteMaintenanceItemResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteMe(context.Context, DeleteMeRequestObject) (DeleteMeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteNote(context.Context, DeleteNoteRequestObject) (DeleteNoteResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteOdometerReading(context.Context, DeleteOdometerReadingRequestObject) (DeleteOdometerReadingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteOilEntry(context.Context, DeleteOilEntryRequestObject) (DeleteOilEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeletePushEndpoint(context.Context, DeletePushEndpointRequestObject) (DeletePushEndpointResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteServiceEntry(context.Context, DeleteServiceEntryRequestObject) (DeleteServiceEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteVehicle(context.Context, DeleteVehicleRequestObject) (DeleteVehicleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DeleteWebhook(context.Context, DeleteWebhookRequestObject) (DeleteWebhookResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DismissCostOccurrence(context.Context, DismissCostOccurrenceRequestObject) (DismissCostOccurrenceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DownloadFile(context.Context, DownloadFileRequestObject) (DownloadFileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) DownloadOriginal(context.Context, DownloadOriginalRequestObject) (DownloadOriginalResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ExchangeToken(context.Context, ExchangeTokenRequestObject) (ExchangeTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) FinishTrip(context.Context, FinishTripRequestObject) (FinishTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetAssistantStatus(context.Context, GetAssistantStatusRequestObject) (GetAssistantStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetChangeFeed(context.Context, GetChangeFeedRequestObject) (GetChangeFeedResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetConsumptionSummary(context.Context, GetConsumptionSummaryRequestObject) (GetConsumptionSummaryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetCostEntry(context.Context, GetCostEntryRequestObject) (GetCostEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetCostPlan(context.Context, GetCostPlanRequestObject) (GetCostPlanResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetCostReport(context.Context, GetCostReportRequestObject) (GetCostReportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetCurrentOdometer(context.Context, GetCurrentOdometerRequestObject) (GetCurrentOdometerResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetDocument(context.Context, GetDocumentRequestObject) (GetDocumentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetDueFeed(context.Context, GetDueFeedRequestObject) (GetDueFeedResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetFile(context.Context, GetFileRequestObject) (GetFileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetFleetCostReport(context.Context, GetFleetCostReportRequestObject) (GetFleetCostReportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetFuelFill(context.Context, GetFuelFillRequestObject) (GetFuelFillResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetHealth(context.Context, GetHealthRequestObject) (GetHealthResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetImport(context.Context, GetImportRequestObject) (GetImportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetMaintenanceItem(context.Context, GetMaintenanceItemRequestObject) (GetMaintenanceItemResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetMaintenanceStatus(context.Context, GetMaintenanceStatusRequestObject) (GetMaintenanceStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetMe(context.Context, GetMeRequestObject) (GetMeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetNote(context.Context, GetNoteRequestObject) (GetNoteResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetNotificationPreferences(context.Context, GetNotificationPreferencesRequestObject) (GetNotificationPreferencesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetOdometerDistance(context.Context, GetOdometerDistanceRequestObject) (GetOdometerDistanceResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetOdometerReading(context.Context, GetOdometerReadingRequestObject) (GetOdometerReadingResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetOdometerValueAt(context.Context, GetOdometerValueAtRequestObject) (GetOdometerValueAtResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetOilEntry(context.Context, GetOilEntryRequestObject) (GetOilEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetOilStatistics(context.Context, GetOilStatisticsRequestObject) (GetOilStatisticsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetServiceEntry(context.Context, GetServiceEntryRequestObject) (GetServiceEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetServiceSummary(context.Context, GetServiceSummaryRequestObject) (GetServiceSummaryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetSettings(context.Context, GetSettingsRequestObject) (GetSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetSetupStatus(context.Context, GetSetupStatusRequestObject) (GetSetupStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetTrip(context.Context, GetTripRequestObject) (GetTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetTripHistory(context.Context, GetTripHistoryRequestObject) (GetTripHistoryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetTripReport(context.Context, GetTripReportRequestObject) (GetTripReportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetVehicle(context.Context, GetVehicleRequestObject) (GetVehicleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GetVehicleDashboard(context.Context, GetVehicleDashboardRequestObject) (GetVehicleDashboardResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) GiveAssistantConsent(context.Context, GiveAssistantConsentRequestObject) (GiveAssistantConsentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListApiTokens(context.Context, ListApiTokensRequestObject) (ListApiTokensResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListAssistantMessages(context.Context, ListAssistantMessagesRequestObject) (ListAssistantMessagesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListAttachments(context.Context, ListAttachmentsRequestObject) (ListAttachmentsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListAuditEvents(context.Context, ListAuditEventsRequestObject) (ListAuditEventsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListCompletions(context.Context, ListCompletionsRequestObject) (ListCompletionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListConversations(context.Context, ListConversationsRequestObject) (ListConversationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListCostEntrys(context.Context, ListCostEntrysRequestObject) (ListCostEntrysResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListCostOccurrences(context.Context, ListCostOccurrencesRequestObject) (ListCostOccurrencesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListCostPlans(context.Context, ListCostPlansRequestObject) (ListCostPlansResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListDocuments(context.Context, ListDocumentsRequestObject) (ListDocumentsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListFiles(context.Context, ListFilesRequestObject) (ListFilesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListFuelFills(context.Context, ListFuelFillsRequestObject) (ListFuelFillsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListImportFindings(context.Context, ListImportFindingsRequestObject) (ListImportFindingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListImports(context.Context, ListImportsRequestObject) (ListImportsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListInvitations(context.Context, ListInvitationsRequestObject) (ListInvitationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListMaintenanceItems(context.Context, ListMaintenanceItemsRequestObject) (ListMaintenanceItemsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListMaintenanceTemplates(context.Context, ListMaintenanceTemplatesRequestObject) (ListMaintenanceTemplatesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListMembers(context.Context, ListMembersRequestObject) (ListMembersResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListMyInvitations(context.Context, ListMyInvitationsRequestObject) (ListMyInvitationsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListNotes(context.Context, ListNotesRequestObject) (ListNotesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListOdometerReadings(context.Context, ListOdometerReadingsRequestObject) (ListOdometerReadingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListOdometerSegments(context.Context, ListOdometerSegmentsRequestObject) (ListOdometerSegmentsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListOilEntrys(context.Context, ListOilEntrysRequestObject) (ListOilEntrysResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListOilSeries(context.Context, ListOilSeriesRequestObject) (ListOilSeriesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListPushEndpoints(context.Context, ListPushEndpointsRequestObject) (ListPushEndpointsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListServiceEntrys(context.Context, ListServiceEntrysRequestObject) (ListServiceEntrysResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListSessions(context.Context, ListSessionsRequestObject) (ListSessionsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListTripCategories(context.Context, ListTripCategoriesRequestObject) (ListTripCategoriesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListTrips(context.Context, ListTripsRequestObject) (ListTripsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListVehicleImages(context.Context, ListVehicleImagesRequestObject) (ListVehicleImagesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListVehicles(context.Context, ListVehiclesRequestObject) (ListVehiclesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ListWebhooks(context.Context, ListWebhooksRequestObject) (ListWebhooksResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) Login(context.Context, LoginRequestObject) (LoginResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) Logout(context.Context, LogoutRequestObject) (LogoutResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) PreviewFile(context.Context, PreviewFileRequestObject) (PreviewFileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RejectProposal(context.Context, RejectProposalRequestObject) (RejectProposalResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RemoveMember(context.Context, RemoveMemberRequestObject) (RemoveMemberResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RemoveVehicleImage(context.Context, RemoveVehicleImageRequestObject) (RemoveVehicleImageResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) ReplaceFile(context.Context, ReplaceFileRequestObject) (ReplaceFileResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RequestPasswordReset(context.Context, RequestPasswordResetRequestObject) (RequestPasswordResetResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RestoreVehicle(context.Context, RestoreVehicleRequestObject) (RestoreVehicleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RevokeApiToken(context.Context, RevokeApiTokenRequestObject) (RevokeApiTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RevokeAssistantConsent(context.Context, RevokeAssistantConsentRequestObject) (RevokeAssistantConsentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RevokeInvitation(context.Context, RevokeInvitationRequestObject) (RevokeInvitationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RevokeSession(context.Context, RevokeSessionRequestObject) (RevokeSessionResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) RunImport(context.Context, RunImportRequestObject) (RunImportResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) SearchVehicleContent(context.Context, SearchVehicleContentRequestObject) (SearchVehicleContentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) SendAssistantMessage(context.Context, SendAssistantMessageRequestObject) (SendAssistantMessageResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) SetImportParameters(context.Context, SetImportParametersRequestObject) (SetImportParametersResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) SetNotificationPreferences(context.Context, SetNotificationPreferencesRequestObject) (SetNotificationPreferencesResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) SetupInstallation(context.Context, SetupInstallationRequestObject) (SetupInstallationResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) StartOidcLogin(context.Context, StartOidcLoginRequestObject) (StartOidcLoginResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) StartTrip(context.Context, StartTripRequestObject) (StartTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateCostEntry(context.Context, UpdateCostEntryRequestObject) (UpdateCostEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateCostPlan(context.Context, UpdateCostPlanRequestObject) (UpdateCostPlanResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateDocument(context.Context, UpdateDocumentRequestObject) (UpdateDocumentResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateFuelFill(context.Context, UpdateFuelFillRequestObject) (UpdateFuelFillResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateMaintenanceItem(context.Context, UpdateMaintenanceItemRequestObject) (UpdateMaintenanceItemResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateMe(context.Context, UpdateMeRequestObject) (UpdateMeResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateNote(context.Context, UpdateNoteRequestObject) (UpdateNoteResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateOilEntry(context.Context, UpdateOilEntryRequestObject) (UpdateOilEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateOpenTrip(context.Context, UpdateOpenTripRequestObject) (UpdateOpenTripResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateServiceEntry(context.Context, UpdateServiceEntryRequestObject) (UpdateServiceEntryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateSettings(context.Context, UpdateSettingsRequestObject) (UpdateSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateTripCategory(context.Context, UpdateTripCategoryRequestObject) (UpdateTripCategoryResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UpdateVehicle(context.Context, UpdateVehicleRequestObject) (UpdateVehicleResponseObject, error) {
	return nil, ErrNotImplemented
}

func (NotImplemented) UploadFile(context.Context, UploadFileRequestObject) (UploadFileResponseObject, error) {
	return nil, ErrNotImplemented
}
