// Command genscopes liest api/openapi.yaml und erzeugt die Sicherheitsangaben je
// Operation (x-vectra-scope, Bearer erlaubt) sowie eine JSON-Kopie der
// Spezifikation für /api/v1/openapi.json (ADR-014, ADR-016: deny-by-default).
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

func main() {
	in := flag.String("in", "../../../api/openapi.yaml", "Spezifikation")
	out := flag.String("out", "scopes.gen.go", "Go-Datei")
	jsonOut := flag.String("json", "openapi.gen.json", "JSON-Kopie")
	flag.Parse()
	raw, err := os.ReadFile(*in)
	if err != nil {
		log.Fatal(err)
	}
	var spec struct {
		Paths map[string]map[string]struct {
			OperationID string                `yaml:"operationId"`
			Security    *[]map[string][]string `yaml:"security"`
			Scope       string                `yaml:"x-vectra-scope"`
		} `yaml:"paths"`
	}
	if err := yaml.Unmarshal(raw, &spec); err != nil {
		log.Fatal(err)
	}
	type op struct {
		id, scope string
		bearer    bool
	}
	var ops []op
	for _, methods := range spec.Paths {
		for _, o := range methods {
			if o.OperationID == "" {
				continue
			}
			bearer := false
			if o.Security != nil {
				for _, s := range *o.Security {
					if _, ok := s["bearerToken"]; ok {
						bearer = true
					}
				}
			}
			ops = append(ops, op{id: o.OperationID, scope: o.Scope, bearer: bearer})
		}
	}
	sort.Slice(ops, func(i, j int) bool { return ops[i].id < ops[j].id })
	var b bytes.Buffer
	b.WriteString("// Code generated by genscopes. DO NOT EDIT.\n\npackage api\n\n")
	b.WriteString("// OpSecurity sind die Sicherheitsangaben einer Operation aus der Spezifikation.\ntype OpSecurity struct {\n\tScope  string\n\tBearer bool\n}\n\n")
	b.WriteString("// Security ordnet jeder operationId ihre Angaben zu.\nvar Security = map[string]OpSecurity{\n")
	for _, o := range ops {
		fmt.Fprintf(&b, "\t%q: {Scope: %q, Bearer: %v},\n", o.id, o.scope, o.bearer)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	var doc any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		log.Fatal(err)
	}
	j, err := json.Marshal(doc)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*jsonOut, j, 0o644); err != nil {
		log.Fatal(err)
	}
}
