// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: odometer.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReadings = `-- name: CountReadings :one
SELECT count(*) FROM odometer.reading WHERE vehicle_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountReadings(ctx context.Context, vehicleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReadings, vehicleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReading = `-- name: GetReading :one
SELECT id, vehicle_id, occurred_at, time_zone, time_precision, value, input_value, input_unit, source, source_ref, status, confirmed_anomalies, supersedes_id, photo_file_id, note, origin, created_at, created_by, recorded_at, deleted_at, version FROM odometer.reading WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReading(ctx context.Context, id pgtype.UUID) (OdometerReading, error) {
	row := q.db.QueryRow(ctx, getReading, id)
	var i OdometerReading
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.Value,
		&i.InputValue,
		&i.InputUnit,
		&i.Source,
		&i.SourceRef,
		&i.Status,
		&i.ConfirmedAnomalies,
		&i.SupersedesID,
		&i.PhotoFileID,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getSuccessor = `-- name: GetSuccessor :one
SELECT id FROM odometer.reading WHERE supersedes_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSuccessor(ctx context.Context, supersedesID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSuccessor, supersedesID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertReading = `-- name: InsertReading :one
INSERT INTO odometer.reading (id, vehicle_id, occurred_at, time_zone, time_precision, value, input_value, input_unit,
    source, source_ref, status, confirmed_anomalies, supersedes_id, photo_file_id, note, origin, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, vehicle_id, occurred_at, time_zone, time_precision, value, input_value, input_unit, source, source_ref, status, confirmed_anomalies, supersedes_id, photo_file_id, note, origin, created_at, created_by, recorded_at, deleted_at, version
`

type InsertReadingParams struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	Value              int64
	InputValue         pgtype.Numeric
	InputUnit          string
	Source             string
	SourceRef          pgtype.UUID
	Status             string
	ConfirmedAnomalies []byte
	SupersedesID       pgtype.UUID
	PhotoFileID        pgtype.UUID
	Note               string
	Origin             string
	CreatedBy          pgtype.UUID
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) (OdometerReading, error) {
	row := q.db.QueryRow(ctx, insertReading,
		arg.ID,
		arg.VehicleID,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.Value,
		arg.InputValue,
		arg.InputUnit,
		arg.Source,
		arg.SourceRef,
		arg.Status,
		arg.ConfirmedAnomalies,
		arg.SupersedesID,
		arg.PhotoFileID,
		arg.Note,
		arg.Origin,
		arg.CreatedBy,
	)
	var i OdometerReading
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.Value,
		&i.InputValue,
		&i.InputUnit,
		&i.Source,
		&i.SourceRef,
		&i.Status,
		&i.ConfirmedAnomalies,
		&i.SupersedesID,
		&i.PhotoFileID,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertSegment = `-- name: InsertSegment :one
INSERT INTO odometer.segment (id, vehicle_id, sequence_no, started_at, time_zone, start_meter_value, "offset", reason, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, vehicle_id, sequence_no, started_at, time_zone, start_meter_value, "offset", reason, note, created_at, created_by
`

type InsertSegmentParams struct {
	ID              pgtype.UUID
	VehicleID       pgtype.UUID
	SequenceNo      int32
	StartedAt       pgtype.Timestamptz
	TimeZone        string
	StartMeterValue int64
	Offset          int64
	Reason          string
	Note            string
	CreatedBy       pgtype.UUID
}

func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) (OdometerSegment, error) {
	row := q.db.QueryRow(ctx, insertSegment,
		arg.ID,
		arg.VehicleID,
		arg.SequenceNo,
		arg.StartedAt,
		arg.TimeZone,
		arg.StartMeterValue,
		arg.Offset,
		arg.Reason,
		arg.Note,
		arg.CreatedBy,
	)
	var i OdometerSegment
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.SequenceNo,
		&i.StartedAt,
		&i.TimeZone,
		&i.StartMeterValue,
		&i.Offset,
		&i.Reason,
		&i.Note,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listReadingsPage = `-- name: ListReadingsPage :many
SELECT id, vehicle_id, occurred_at, time_zone, time_precision, value, input_value, input_unit, source, source_ref, status, confirmed_anomalies, supersedes_id, photo_file_id, note, origin, created_at, created_by, recorded_at, deleted_at, version FROM odometer.reading
WHERE vehicle_id = $1 AND deleted_at IS NULL
  AND ($2::boolean OR status <> 'superseded')
  AND ($3::timestamptz IS NULL OR occurred_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR occurred_at < $4::timestamptz)
  AND ($5::timestamptz IS NULL OR (occurred_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $7
`

type ListReadingsPageParams struct {
	VehicleID         pgtype.UUID
	IncludeSuperseded bool
	FromTs            pgtype.Timestamptz
	ToTs              pgtype.Timestamptz
	BeforeTs          pgtype.Timestamptz
	BeforeID          pgtype.UUID
	Lim               int32
}

func (q *Queries) ListReadingsPage(ctx context.Context, arg ListReadingsPageParams) ([]OdometerReading, error) {
	rows, err := q.db.Query(ctx, listReadingsPage,
		arg.VehicleID,
		arg.IncludeSuperseded,
		arg.FromTs,
		arg.ToTs,
		arg.BeforeTs,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OdometerReading
	for rows.Next() {
		var i OdometerReading
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.OccurredAt,
			&i.TimeZone,
			&i.TimePrecision,
			&i.Value,
			&i.InputValue,
			&i.InputUnit,
			&i.Source,
			&i.SourceRef,
			&i.Status,
			&i.ConfirmedAnomalies,
			&i.SupersedesID,
			&i.PhotoFileID,
			&i.Note,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegments = `-- name: ListSegments :many
SELECT id, vehicle_id, sequence_no, started_at, time_zone, start_meter_value, "offset", reason, note, created_at, created_by FROM odometer.segment WHERE vehicle_id = $1 ORDER BY sequence_no
`

func (q *Queries) ListSegments(ctx context.Context, vehicleID pgtype.UUID) ([]OdometerSegment, error) {
	rows, err := q.db.Query(ctx, listSegments, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OdometerSegment
	for rows.Next() {
		var i OdometerSegment
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.SequenceNo,
			&i.StartedAt,
			&i.TimeZone,
			&i.StartMeterValue,
			&i.Offset,
			&i.Reason,
			&i.Note,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidReadings = `-- name: ListValidReadings :many
SELECT id, vehicle_id, occurred_at, time_zone, time_precision, value, input_value, input_unit, source, source_ref, status, confirmed_anomalies, supersedes_id, photo_file_id, note, origin, created_at, created_by, recorded_at, deleted_at, version FROM odometer.reading
WHERE vehicle_id = $1 AND deleted_at IS NULL AND status <> 'superseded'
ORDER BY occurred_at, recorded_at, id
`

func (q *Queries) ListValidReadings(ctx context.Context, vehicleID pgtype.UUID) ([]OdometerReading, error) {
	rows, err := q.db.Query(ctx, listValidReadings, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OdometerReading
	for rows.Next() {
		var i OdometerReading
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.OccurredAt,
			&i.TimeZone,
			&i.TimePrecision,
			&i.Value,
			&i.InputValue,
			&i.InputUnit,
			&i.Source,
			&i.SourceRef,
			&i.Status,
			&i.ConfirmedAnomalies,
			&i.SupersedesID,
			&i.PhotoFileID,
			&i.Note,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSuperseded = `-- name: MarkSuperseded :execrows
UPDATE odometer.reading SET status = 'superseded', version = version + 1
WHERE id = $1 AND version = $2 AND status <> 'superseded' AND deleted_at IS NULL
`

type MarkSupersededParams struct {
	ID      pgtype.UUID
	Version int32
}

func (q *Queries) MarkSuperseded(ctx context.Context, arg MarkSupersededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSuperseded, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteReading = `-- name: SoftDeleteReading :execrows
UPDATE odometer.reading SET deleted_at = now(), version = version + 1
WHERE id = $1 AND version = $2 AND deleted_at IS NULL
`

type SoftDeleteReadingParams struct {
	ID      pgtype.UUID
	Version int32
}

func (q *Queries) SoftDeleteReading(ctx context.Context, arg SoftDeleteReadingParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReading, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
