// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM identity.account
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, email_verified, display_name, status, is_admin, password_hash, settings, last_login_at, created_at, updated_at, version FROM identity.account WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Settings,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, email_verified, display_name, status, is_admin, password_hash, settings, last_login_at, created_at, updated_at, version FROM identity.account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Settings,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id, s.account_id, s.csrf_token, s.idle_expires_at, s.absolute_expires_at, s.last_seen_at
FROM identity.session s
JOIN identity.account a ON a.id = s.account_id
WHERE s.token_hash = $1 AND s.revoked_at IS NULL
  AND s.idle_expires_at > now() AND s.absolute_expires_at > now()
  AND a.status = 'active'
`

type GetActiveSessionRow struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	CsrfToken         string
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
}

func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CsrfToken,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT role FROM identity.vehicle_membership WHERE vehicle_id = $1 AND account_id = $2
`

type GetRoleParams struct {
	VehicleID pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getRole, arg.VehicleID, arg.AccountID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO identity.account (id, email, display_name, status, is_admin, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_verified, display_name, status, is_admin, password_hash, settings, last_login_at, created_at, updated_at, version
`

type InsertAccountParams struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	Status       string
	IsAdmin      bool
	PasswordHash pgtype.Text
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Status,
		arg.IsAdmin,
		arg.PasswordHash,
	)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Settings,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO identity.vehicle_membership (vehicle_id, account_id, role) VALUES ($1, $2, $3)
`

type InsertMembershipParams struct {
	VehicleID pgtype.UUID
	AccountID pgtype.UUID
	Role      string
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership, arg.VehicleID, arg.AccountID, arg.Role)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO identity.session (id, account_id, token_hash, csrf_token, client_kind, user_agent, idle_expires_at, absolute_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSessionParams struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	TokenHash         []byte
	CsrfToken         string
	ClientKind        string
	UserAgent         string
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.CsrfToken,
		arg.ClientKind,
		arg.UserAgent,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const listMemberVehicleIDs = `-- name: ListMemberVehicleIDs :many
SELECT vehicle_id, role FROM identity.vehicle_membership WHERE account_id = $1
`

type ListMemberVehicleIDsRow struct {
	VehicleID pgtype.UUID
	Role      string
}

func (q *Queries) ListMemberVehicleIDs(ctx context.Context, accountID pgtype.UUID) ([]ListMemberVehicleIDsRow, error) {
	rows, err := q.db.Query(ctx, listMemberVehicleIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberVehicleIDsRow
	for rows.Next() {
		var i ListMemberVehicleIDsRow
		if err := rows.Scan(&i.VehicleID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, client_kind, user_agent, created_at, last_seen_at FROM identity.session
WHERE account_id = $1 AND revoked_at IS NULL AND idle_expires_at > now() AND absolute_expires_at > now()
ORDER BY last_seen_at DESC
`

type ListSessionsRow struct {
	ID         pgtype.UUID
	ClientKind string
	UserAgent  string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) ListSessions(ctx context.Context, accountID pgtype.UUID) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientKind,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLogin = `-- name: MarkLogin :exec
UPDATE identity.account SET last_login_at = now() WHERE id = $1
`

func (q *Queries) MarkLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markLogin, id)
	return err
}

const revokeOwnSession = `-- name: RevokeOwnSession :execrows
UPDATE identity.session SET revoked_at = now() WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokeOwnSessionParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) RevokeOwnSession(ctx context.Context, arg RevokeOwnSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOwnSession, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE identity.session SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE identity.session SET last_seen_at = now(), idle_expires_at = LEAST($2, absolute_expires_at) WHERE id = $1
`

type TouchSessionParams struct {
	ID            pgtype.UUID
	IdleExpiresAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.IdleExpiresAt)
	return err
}

const updateAccountDisplayName = `-- name: UpdateAccountDisplayName :one
UPDATE identity.account SET display_name = $2, updated_at = now(), version = version + 1 WHERE id = $1 RETURNING id, email, email_verified, display_name, status, is_admin, password_hash, settings, last_login_at, created_at, updated_at, version
`

type UpdateAccountDisplayNameParams struct {
	ID          pgtype.UUID
	DisplayName string
}

func (q *Queries) UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountDisplayName, arg.ID, arg.DisplayName)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Settings,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateAccountSettings = `-- name: UpdateAccountSettings :one
UPDATE identity.account SET settings = $2, updated_at = now(), version = version + 1 WHERE id = $1 RETURNING id, email, email_verified, display_name, status, is_admin, password_hash, settings, last_login_at, created_at, updated_at, version
`

type UpdateAccountSettingsParams struct {
	ID       pgtype.UUID
	Settings []byte
}

func (q *Queries) UpdateAccountSettings(ctx context.Context, arg UpdateAccountSettingsParams) (IdentityAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountSettings, arg.ID, arg.Settings)
	var i IdentityAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.Settings,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
