// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID             pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	ActorAccountID pgtype.UUID
	ActorKind      string
	Action         string
	VehicleID      pgtype.UUID
	ObjectType     string
	ObjectID       pgtype.UUID
	Changes        []byte
	Reason         pgtype.Text
	RequestID      pgtype.Text
}

type IdentityAccount struct {
	ID            pgtype.UUID
	Email         string
	EmailVerified bool
	DisplayName   string
	Status        string
	IsAdmin       bool
	PasswordHash  pgtype.Text
	Settings      []byte
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
}

type IdentitySession struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	TokenHash         []byte
	CsrfToken         string
	ClientKind        string
	UserAgent         string
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type IdentityVehicleMembership struct {
	VehicleID pgtype.UUID
	AccountID pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type OdometerReading struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	Value              int64
	InputValue         pgtype.Numeric
	InputUnit          string
	Source             string
	SourceRef          pgtype.UUID
	Status             string
	ConfirmedAnomalies []byte
	SupersedesID       pgtype.UUID
	PhotoFileID        pgtype.UUID
	Note               string
	Origin             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	RecordedAt         pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Version            int32
}

type OdometerSegment struct {
	ID              pgtype.UUID
	VehicleID       pgtype.UUID
	SequenceNo      int32
	StartedAt       pgtype.Timestamptz
	TimeZone        string
	StartMeterValue int64
	Offset          int64
	Reason          string
	Note            string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
}

type VehiclesVehicle struct {
	ID                pgtype.UUID
	DisplayName       string
	Vin               pgtype.Text
	LicensePlate      pgtype.Text
	PlateCountry      pgtype.Text
	Make              pgtype.Text
	Model             pgtype.Text
	Variant           pgtype.Text
	ModelYear         pgtype.Int4
	FirstRegistration pgtype.Date
	BodyType          string
	EngineCode        pgtype.Text
	DisplacementCcm   pgtype.Int4
	PowerKw           pgtype.Int4
	Transmission      pgtype.Text
	UsageMeter        string
	EnergyCarriers    []string
	OdometerRequired  bool
	OwnerTimeZone     string
	DefaultCurrency   string
	Status            string
	PurchaseDate      pgtype.Date
	PurchaseAmount    pgtype.Int8
	PurchaseCurrency  pgtype.Text
	SaleDate          pgtype.Date
	SaleAmount        pgtype.Int8
	SaleCurrency      pgtype.Text
	Note              string
	Tags              []string
	Extra             []byte
	Origin            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	RecordedAt        pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	Version           int32
}
