// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maintenance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompletion = `-- name: GetCompletion :one
SELECT id, item_id, vehicle_id, kind, completed_on, completed_total, completed_input, service_entry_id, reason, idempotency_key, created_at, created_by, deleted_at FROM maintenance.completion WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompletion(ctx context.Context, id pgtype.UUID) (MaintenanceCompletion, error) {
	row := q.db.QueryRow(ctx, getCompletion, id)
	var i MaintenanceCompletion
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.VehicleID,
		&i.Kind,
		&i.CompletedOn,
		&i.CompletedTotal,
		&i.CompletedInput,
		&i.ServiceEntryID,
		&i.Reason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getCompletionByKey = `-- name: GetCompletionByKey :one
SELECT id, item_id, vehicle_id, kind, completed_on, completed_total, completed_input, service_entry_id, reason, idempotency_key, created_at, created_by, deleted_at FROM maintenance.completion WHERE item_id = $1 AND idempotency_key = $2
`

type GetCompletionByKeyParams struct {
	ItemID         pgtype.UUID
	IdempotencyKey pgtype.Text
}

func (q *Queries) GetCompletionByKey(ctx context.Context, arg GetCompletionByKeyParams) (MaintenanceCompletion, error) {
	row := q.db.QueryRow(ctx, getCompletionByKey, arg.ItemID, arg.IdempotencyKey)
	var i MaintenanceCompletion
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.VehicleID,
		&i.Kind,
		&i.CompletedOn,
		&i.CompletedTotal,
		&i.CompletedInput,
		&i.ServiceEntryID,
		&i.Reason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, vehicle_id, title, description, category, manufacturer_recommended, source_document_id, source_page, schedule_mode, interval_months, interval_days, interval_distance, anchor_date, anchor_total, due_date_once, due_total_once, upcoming_days, due_days, upcoming_distance, due_distance, inputs, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM maintenance.item WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetItem(ctx context.Context, id pgtype.UUID) (MaintenanceItem, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i MaintenanceItem
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ManufacturerRecommended,
		&i.SourceDocumentID,
		&i.SourcePage,
		&i.ScheduleMode,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.IntervalDistance,
		&i.AnchorDate,
		&i.AnchorTotal,
		&i.DueDateOnce,
		&i.DueTotalOnce,
		&i.UpcomingDays,
		&i.DueDays,
		&i.UpcomingDistance,
		&i.DueDistance,
		&i.Inputs,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getItemAny = `-- name: GetItemAny :one
SELECT id, vehicle_id, title, description, category, manufacturer_recommended, source_document_id, source_page, schedule_mode, interval_months, interval_days, interval_distance, anchor_date, anchor_total, due_date_once, due_total_once, upcoming_days, due_days, upcoming_distance, due_distance, inputs, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM maintenance.item WHERE id = $1
`

func (q *Queries) GetItemAny(ctx context.Context, id pgtype.UUID) (MaintenanceItem, error) {
	row := q.db.QueryRow(ctx, getItemAny, id)
	var i MaintenanceItem
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ManufacturerRecommended,
		&i.SourceDocumentID,
		&i.SourcePage,
		&i.ScheduleMode,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.IntervalDistance,
		&i.AnchorDate,
		&i.AnchorTotal,
		&i.DueDateOnce,
		&i.DueTotalOnce,
		&i.UpcomingDays,
		&i.DueDays,
		&i.UpcomingDistance,
		&i.DueDistance,
		&i.Inputs,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertCompletion = `-- name: InsertCompletion :one
INSERT INTO maintenance.completion (id, item_id, vehicle_id, kind, completed_on, completed_total, completed_input, reason, idempotency_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, item_id, vehicle_id, kind, completed_on, completed_total, completed_input, service_entry_id, reason, idempotency_key, created_at, created_by, deleted_at
`

type InsertCompletionParams struct {
	ID             pgtype.UUID
	ItemID         pgtype.UUID
	VehicleID      pgtype.UUID
	Kind           string
	CompletedOn    pgtype.Date
	CompletedTotal pgtype.Int8
	CompletedInput []byte
	Reason         pgtype.Text
	IdempotencyKey pgtype.Text
	CreatedBy      pgtype.UUID
}

func (q *Queries) InsertCompletion(ctx context.Context, arg InsertCompletionParams) (MaintenanceCompletion, error) {
	row := q.db.QueryRow(ctx, insertCompletion,
		arg.ID,
		arg.ItemID,
		arg.VehicleID,
		arg.Kind,
		arg.CompletedOn,
		arg.CompletedTotal,
		arg.CompletedInput,
		arg.Reason,
		arg.IdempotencyKey,
		arg.CreatedBy,
	)
	var i MaintenanceCompletion
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.VehicleID,
		&i.Kind,
		&i.CompletedOn,
		&i.CompletedTotal,
		&i.CompletedInput,
		&i.ServiceEntryID,
		&i.Reason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO maintenance.item (id, vehicle_id, title, description, category, manufacturer_recommended, source_document_id, source_page,
    schedule_mode, interval_months, interval_days, interval_distance, anchor_date, anchor_total, due_date_once, due_total_once,
    upcoming_days, due_days, upcoming_distance, due_distance, inputs, active, note, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $25)
RETURNING id, vehicle_id, title, description, category, manufacturer_recommended, source_document_id, source_page, schedule_mode, interval_months, interval_days, interval_distance, anchor_date, anchor_total, due_date_once, due_total_once, upcoming_days, due_days, upcoming_distance, due_distance, inputs, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertItemParams struct {
	ID                      pgtype.UUID
	VehicleID               pgtype.UUID
	Title                   string
	Description             pgtype.Text
	Category                string
	ManufacturerRecommended bool
	SourceDocumentID        pgtype.UUID
	SourcePage              pgtype.Int4
	ScheduleMode            string
	IntervalMonths          pgtype.Int4
	IntervalDays            pgtype.Int4
	IntervalDistance        pgtype.Int8
	AnchorDate              pgtype.Date
	AnchorTotal             pgtype.Int8
	DueDateOnce             pgtype.Date
	DueTotalOnce            pgtype.Int8
	UpcomingDays            pgtype.Int4
	DueDays                 pgtype.Int4
	UpcomingDistance        pgtype.Int8
	DueDistance             pgtype.Int8
	Inputs                  []byte
	Active                  bool
	Note                    string
	Origin                  string
	CreatedBy               pgtype.UUID
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (MaintenanceItem, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.ID,
		arg.VehicleID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ManufacturerRecommended,
		arg.SourceDocumentID,
		arg.SourcePage,
		arg.ScheduleMode,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.IntervalDistance,
		arg.AnchorDate,
		arg.AnchorTotal,
		arg.DueDateOnce,
		arg.DueTotalOnce,
		arg.UpcomingDays,
		arg.DueDays,
		arg.UpcomingDistance,
		arg.DueDistance,
		arg.Inputs,
		arg.Active,
		arg.Note,
		arg.Origin,
		arg.CreatedBy,
	)
	var i MaintenanceItem
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ManufacturerRecommended,
		&i.SourceDocumentID,
		&i.SourcePage,
		&i.ScheduleMode,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.IntervalDistance,
		&i.AnchorDate,
		&i.AnchorTotal,
		&i.DueDateOnce,
		&i.DueTotalOnce,
		&i.UpcomingDays,
		&i.DueDays,
		&i.UpcomingDistance,
		&i.DueDistance,
		&i.Inputs,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listCompletions = `-- name: ListCompletions :many
SELECT id, item_id, vehicle_id, kind, completed_on, completed_total, completed_input, service_entry_id, reason, idempotency_key, created_at, created_by, deleted_at FROM maintenance.completion WHERE item_id = $1 AND deleted_at IS NULL ORDER BY completed_on DESC, id DESC
`

func (q *Queries) ListCompletions(ctx context.Context, itemID pgtype.UUID) ([]MaintenanceCompletion, error) {
	rows, err := q.db.Query(ctx, listCompletions, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceCompletion
	for rows.Next() {
		var i MaintenanceCompletion
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.VehicleID,
			&i.Kind,
			&i.CompletedOn,
			&i.CompletedTotal,
			&i.CompletedInput,
			&i.ServiceEntryID,
			&i.Reason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionsForVehicle = `-- name: ListCompletionsForVehicle :many
SELECT id, item_id, vehicle_id, kind, completed_on, completed_total, completed_input, service_entry_id, reason, idempotency_key, created_at, created_by, deleted_at FROM maintenance.completion WHERE vehicle_id = $1 AND deleted_at IS NULL ORDER BY completed_on, id
`

func (q *Queries) ListCompletionsForVehicle(ctx context.Context, vehicleID pgtype.UUID) ([]MaintenanceCompletion, error) {
	rows, err := q.db.Query(ctx, listCompletionsForVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceCompletion
	for rows.Next() {
		var i MaintenanceCompletion
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.VehicleID,
			&i.Kind,
			&i.CompletedOn,
			&i.CompletedTotal,
			&i.CompletedInput,
			&i.ServiceEntryID,
			&i.Reason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, vehicle_id, title, description, category, manufacturer_recommended, source_document_id, source_page, schedule_mode, interval_months, interval_days, interval_distance, anchor_date, anchor_total, due_date_once, due_total_once, upcoming_days, due_days, upcoming_distance, due_distance, inputs, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM maintenance.item
WHERE vehicle_id = $1 AND ($2::boolean OR deleted_at IS NULL)
ORDER BY title, id
`

type ListItemsParams struct {
	VehicleID      pgtype.UUID
	IncludeDeleted bool
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]MaintenanceItem, error) {
	rows, err := q.db.Query(ctx, listItems, arg.VehicleID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceItem
	for rows.Next() {
		var i MaintenanceItem
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ManufacturerRecommended,
			&i.SourceDocumentID,
			&i.SourcePage,
			&i.ScheduleMode,
			&i.IntervalMonths,
			&i.IntervalDays,
			&i.IntervalDistance,
			&i.AnchorDate,
			&i.AnchorTotal,
			&i.DueDateOnce,
			&i.DueTotalOnce,
			&i.UpcomingDays,
			&i.DueDays,
			&i.UpcomingDistance,
			&i.DueDistance,
			&i.Inputs,
			&i.Active,
			&i.Note,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCompletion = `-- name: SoftDeleteCompletion :execrows
UPDATE maintenance.completion SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCompletion(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCompletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteItem = `-- name: SoftDeleteItem :execrows
UPDATE maintenance.item SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteItemParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteItem, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE maintenance.item SET title = $2, description = $3, category = $4, manufacturer_recommended = $5, source_document_id = $6,
    source_page = $7, schedule_mode = $8, interval_months = $9, interval_days = $10, interval_distance = $11, anchor_date = $12,
    anchor_total = $13, due_date_once = $14, due_total_once = $15, upcoming_days = $16, due_days = $17, upcoming_distance = $18,
    due_distance = $19, inputs = $20, active = $21, note = $22, updated_by = $23, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $24 AND deleted_at IS NULL
RETURNING id, vehicle_id, title, description, category, manufacturer_recommended, source_document_id, source_page, schedule_mode, interval_months, interval_days, interval_distance, anchor_date, anchor_total, due_date_once, due_total_once, upcoming_days, due_days, upcoming_distance, due_distance, inputs, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateItemParams struct {
	ID                      pgtype.UUID
	Title                   string
	Description             pgtype.Text
	Category                string
	ManufacturerRecommended bool
	SourceDocumentID        pgtype.UUID
	SourcePage              pgtype.Int4
	ScheduleMode            string
	IntervalMonths          pgtype.Int4
	IntervalDays            pgtype.Int4
	IntervalDistance        pgtype.Int8
	AnchorDate              pgtype.Date
	AnchorTotal             pgtype.Int8
	DueDateOnce             pgtype.Date
	DueTotalOnce            pgtype.Int8
	UpcomingDays            pgtype.Int4
	DueDays                 pgtype.Int4
	UpcomingDistance        pgtype.Int8
	DueDistance             pgtype.Int8
	Inputs                  []byte
	Active                  bool
	Note                    string
	UpdatedBy               pgtype.UUID
	Version                 int32
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (MaintenanceItem, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ManufacturerRecommended,
		arg.SourceDocumentID,
		arg.SourcePage,
		arg.ScheduleMode,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.IntervalDistance,
		arg.AnchorDate,
		arg.AnchorTotal,
		arg.DueDateOnce,
		arg.DueTotalOnce,
		arg.UpcomingDays,
		arg.DueDays,
		arg.UpcomingDistance,
		arg.DueDistance,
		arg.Inputs,
		arg.Active,
		arg.Note,
		arg.UpdatedBy,
		arg.Version,
	)
	var i MaintenanceItem
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ManufacturerRecommended,
		&i.SourceDocumentID,
		&i.SourcePage,
		&i.ScheduleMode,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.IntervalDistance,
		&i.AnchorDate,
		&i.AnchorTotal,
		&i.DueDateOnce,
		&i.DueTotalOnce,
		&i.UpcomingDays,
		&i.DueDays,
		&i.UpcomingDistance,
		&i.DueDistance,
		&i.Inputs,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
