// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryImage = `-- name: ClearPrimaryImage :exec
UPDATE documents.vehicle_image SET is_primary = false WHERE vehicle_id = $1 AND is_primary
`

func (q *Queries) ClearPrimaryImage(ctx context.Context, vehicleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryImage, vehicleID)
	return err
}

const deleteDocumentFiles = `-- name: DeleteDocumentFiles :exec
DELETE FROM documents.document_file WHERE document_id = $1
`

func (q *Queries) DeleteDocumentFiles(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentFiles, documentID)
	return err
}

const deleteImage = `-- name: DeleteImage :execrows
DELETE FROM documents.vehicle_image WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteImage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const documentFiles = `-- name: DocumentFiles :many
SELECT document_id, file_id FROM documents.document_file WHERE document_id = ANY($1::uuid[]) ORDER BY document_id, position
`

type DocumentFilesRow struct {
	DocumentID pgtype.UUID
	FileID     pgtype.UUID
}

func (q *Queries) DocumentFiles(ctx context.Context, ids []pgtype.UUID) ([]DocumentFilesRow, error) {
	rows, err := q.db.Query(ctx, documentFiles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentFilesRow
	for rows.Next() {
		var i DocumentFilesRow
		if err := rows.Scan(&i.DocumentID, &i.FileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileBySha = `-- name: FileBySha :one
SELECT id, vehicle_id, storage_key, original_name, media_type, size_bytes, sha256, received_at, captured_at_client, capture_source, derivatives, has_location, supersedes_id, replace_reason, upload_time_origin, created_by, deleted_at FROM documents.file WHERE vehicle_id = $1 AND sha256 = $2 AND deleted_at IS NULL ORDER BY received_at LIMIT 1
`

type FileByShaParams struct {
	VehicleID pgtype.UUID
	Sha256    string
}

func (q *Queries) FileBySha(ctx context.Context, arg FileByShaParams) (DocumentsFile, error) {
	row := q.db.QueryRow(ctx, fileBySha, arg.VehicleID, arg.Sha256)
	var i DocumentsFile
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.StorageKey,
		&i.OriginalName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ReceivedAt,
		&i.CapturedAtClient,
		&i.CaptureSource,
		&i.Derivatives,
		&i.HasLocation,
		&i.SupersedesID,
		&i.ReplaceReason,
		&i.UploadTimeOrigin,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const fileReferences = `-- name: FileReferences :one
SELECT (SELECT count(*) FROM documents.document_file df JOIN documents.document d ON d.id = df.document_id WHERE df.file_id = $1 AND d.deleted_at IS NULL)
     + (SELECT count(*) FROM documents.attachment a WHERE a.file_id = $1 AND a.deleted_at IS NULL)
     + (SELECT count(*) FROM documents.vehicle_image i WHERE i.file_id = $1) AS refs
`

func (q *Queries) FileReferences(ctx context.Context, fileID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, fileReferences, fileID)
	var refs int32
	err := row.Scan(&refs)
	return refs, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, vehicle_id, file_id, document_id, target_type, target_id, role, page, created_at, created_by, deleted_at FROM documents.attachment WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id pgtype.UUID) (DocumentsAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i DocumentsAttachment
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.FileID,
		&i.DocumentID,
		&i.TargetType,
		&i.TargetID,
		&i.Role,
		&i.Page,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, vehicle_id, doc_type, nature, title, document_date, issuer, language, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM documents.document WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (DocumentsDocument, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i DocumentsDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DocType,
		&i.Nature,
		&i.Title,
		&i.DocumentDate,
		&i.Issuer,
		&i.Language,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, vehicle_id, storage_key, original_name, media_type, size_bytes, sha256, received_at, captured_at_client, capture_source, derivatives, has_location, supersedes_id, replace_reason, upload_time_origin, created_by, deleted_at FROM documents.file WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (DocumentsFile, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i DocumentsFile
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.StorageKey,
		&i.OriginalName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ReceivedAt,
		&i.CapturedAtClient,
		&i.CaptureSource,
		&i.Derivatives,
		&i.HasLocation,
		&i.SupersedesID,
		&i.ReplaceReason,
		&i.UploadTimeOrigin,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, vehicle_id, file_id, is_primary, created_at, created_by FROM documents.vehicle_image WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id pgtype.UUID) (DocumentsVehicleImage, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i DocumentsVehicleImage
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.FileID,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO documents.attachment (id, vehicle_id, file_id, document_id, target_type, target_id, role, page, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, vehicle_id, file_id, document_id, target_type, target_id, role, page, created_at, created_by, deleted_at
`

type InsertAttachmentParams struct {
	ID         pgtype.UUID
	VehicleID  pgtype.UUID
	FileID     pgtype.UUID
	DocumentID pgtype.UUID
	TargetType string
	TargetID   pgtype.UUID
	Role       string
	Page       pgtype.Int4
	CreatedBy  pgtype.UUID
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (DocumentsAttachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.ID,
		arg.VehicleID,
		arg.FileID,
		arg.DocumentID,
		arg.TargetType,
		arg.TargetID,
		arg.Role,
		arg.Page,
		arg.CreatedBy,
	)
	var i DocumentsAttachment
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.FileID,
		&i.DocumentID,
		&i.TargetType,
		&i.TargetID,
		&i.Role,
		&i.Page,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents.document (id, vehicle_id, doc_type, nature, title, document_date, issuer, language, note, tags, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12)
RETURNING id, vehicle_id, doc_type, nature, title, document_date, issuer, language, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertDocumentParams struct {
	ID           pgtype.UUID
	VehicleID    pgtype.UUID
	DocType      string
	Nature       string
	Title        string
	DocumentDate pgtype.Date
	Issuer       pgtype.Text
	Language     pgtype.Text
	Note         string
	Tags         []string
	Origin       string
	CreatedBy    pgtype.UUID
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (DocumentsDocument, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.VehicleID,
		arg.DocType,
		arg.Nature,
		arg.Title,
		arg.DocumentDate,
		arg.Issuer,
		arg.Language,
		arg.Note,
		arg.Tags,
		arg.Origin,
		arg.CreatedBy,
	)
	var i DocumentsDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DocType,
		&i.Nature,
		&i.Title,
		&i.DocumentDate,
		&i.Issuer,
		&i.Language,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertDocumentFile = `-- name: InsertDocumentFile :exec
INSERT INTO documents.document_file (document_id, position, file_id) VALUES ($1, $2, $3)
`

type InsertDocumentFileParams struct {
	DocumentID pgtype.UUID
	Position   int32
	FileID     pgtype.UUID
}

func (q *Queries) InsertDocumentFile(ctx context.Context, arg InsertDocumentFileParams) error {
	_, err := q.db.Exec(ctx, insertDocumentFile, arg.DocumentID, arg.Position, arg.FileID)
	return err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO documents.file (id, vehicle_id, storage_key, original_name, media_type, size_bytes, sha256, captured_at_client, capture_source,
    derivatives, has_location, supersedes_id, replace_reason, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, vehicle_id, storage_key, original_name, media_type, size_bytes, sha256, received_at, captured_at_client, capture_source, derivatives, has_location, supersedes_id, replace_reason, upload_time_origin, created_by, deleted_at
`

type InsertFileParams struct {
	ID               pgtype.UUID
	VehicleID        pgtype.UUID
	StorageKey       string
	OriginalName     string
	MediaType        string
	SizeBytes        int64
	Sha256           string
	CapturedAtClient pgtype.Timestamptz
	CaptureSource    pgtype.Text
	Derivatives      []string
	HasLocation      bool
	SupersedesID     pgtype.UUID
	ReplaceReason    pgtype.Text
	CreatedBy        pgtype.UUID
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (DocumentsFile, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.ID,
		arg.VehicleID,
		arg.StorageKey,
		arg.OriginalName,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.CapturedAtClient,
		arg.CaptureSource,
		arg.Derivatives,
		arg.HasLocation,
		arg.SupersedesID,
		arg.ReplaceReason,
		arg.CreatedBy,
	)
	var i DocumentsFile
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.StorageKey,
		&i.OriginalName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.ReceivedAt,
		&i.CapturedAtClient,
		&i.CaptureSource,
		&i.Derivatives,
		&i.HasLocation,
		&i.SupersedesID,
		&i.ReplaceReason,
		&i.UploadTimeOrigin,
		&i.CreatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, vehicle_id, file_id, document_id, target_type, target_id, role, page, created_at, created_by, deleted_at FROM documents.attachment
WHERE vehicle_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR target_type = $2::text)
  AND ($3::uuid IS NULL OR target_id = $3::uuid)
ORDER BY created_at, id
`

type ListAttachmentsParams struct {
	VehicleID  pgtype.UUID
	TargetType pgtype.Text
	TargetID   pgtype.UUID
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]DocumentsAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.VehicleID, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentsAttachment
	for rows.Next() {
		var i DocumentsAttachment
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.FileID,
			&i.DocumentID,
			&i.TargetType,
			&i.TargetID,
			&i.Role,
			&i.Page,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, vehicle_id, doc_type, nature, title, document_date, issuer, language, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM documents.document d
WHERE d.vehicle_id = $1 AND d.deleted_at IS NULL
  AND ($2::text IS NULL OR d.doc_type = $2::text)
  AND ($3::text IS NULL OR d.nature = $3::text)
  AND ($4::text IS NULL OR d.title ILIKE '%' || $4::text || '%' OR d.issuer ILIKE '%' || $4::text || '%'
       OR d.note ILIKE '%' || $4::text || '%' OR array_to_string(d.tags, ' ') ILIKE '%' || $4::text || '%')
ORDER BY coalesce(d.document_date, d.created_at::date) DESC, d.id DESC
LIMIT $5
`

type ListDocumentsParams struct {
	VehicleID pgtype.UUID
	DocType   pgtype.Text
	Nature    pgtype.Text
	Q         pgtype.Text
	Lim       int32
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]DocumentsDocument, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.VehicleID,
		arg.DocType,
		arg.Nature,
		arg.Q,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentsDocument
	for rows.Next() {
		var i DocumentsDocument
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.DocType,
			&i.Nature,
			&i.Title,
			&i.DocumentDate,
			&i.Issuer,
			&i.Language,
			&i.Note,
			&i.Tags,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, vehicle_id, storage_key, original_name, media_type, size_bytes, sha256, received_at, captured_at_client, capture_source, derivatives, has_location, supersedes_id, replace_reason, upload_time_origin, created_by, deleted_at FROM documents.file
WHERE vehicle_id = $1 AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL OR (received_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY received_at DESC, id DESC
LIMIT $4
`

type ListFilesParams struct {
	VehicleID pgtype.UUID
	BeforeTs  pgtype.Timestamptz
	BeforeID  pgtype.UUID
	Lim       int32
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]DocumentsFile, error) {
	rows, err := q.db.Query(ctx, listFiles,
		arg.VehicleID,
		arg.BeforeTs,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentsFile
	for rows.Next() {
		var i DocumentsFile
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.StorageKey,
			&i.OriginalName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Sha256,
			&i.ReceivedAt,
			&i.CapturedAtClient,
			&i.CaptureSource,
			&i.Derivatives,
			&i.HasLocation,
			&i.SupersedesID,
			&i.ReplaceReason,
			&i.UploadTimeOrigin,
			&i.CreatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
SELECT id, vehicle_id, file_id, is_primary, created_at, created_by FROM documents.vehicle_image WHERE vehicle_id = $1 ORDER BY is_primary DESC, created_at
`

func (q *Queries) ListImages(ctx context.Context, vehicleID pgtype.UUID) ([]DocumentsVehicleImage, error) {
	rows, err := q.db.Query(ctx, listImages, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentsVehicleImage
	for rows.Next() {
		var i DocumentsVehicleImage
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.FileID,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteFirstImage = `-- name: PromoteFirstImage :exec
UPDATE documents.vehicle_image vi SET is_primary = true
WHERE vi.id = (SELECT x.id FROM documents.vehicle_image x WHERE x.vehicle_id = $1 ORDER BY x.created_at LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM documents.vehicle_image y WHERE y.vehicle_id = $1 AND y.is_primary)
`

func (q *Queries) PromoteFirstImage(ctx context.Context, vehicleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteFirstImage, vehicleID)
	return err
}

const repointAttachments = `-- name: RepointAttachments :exec
UPDATE documents.attachment SET file_id = $1 WHERE file_id = $2 AND deleted_at IS NULL
`

type RepointAttachmentsParams struct {
	NewID pgtype.UUID
	OldID pgtype.UUID
}

func (q *Queries) RepointAttachments(ctx context.Context, arg RepointAttachmentsParams) error {
	_, err := q.db.Exec(ctx, repointAttachments, arg.NewID, arg.OldID)
	return err
}

const repointDocumentFiles = `-- name: RepointDocumentFiles :exec
UPDATE documents.document_file SET file_id = $1 WHERE file_id = $2
`

type RepointDocumentFilesParams struct {
	NewID pgtype.UUID
	OldID pgtype.UUID
}

func (q *Queries) RepointDocumentFiles(ctx context.Context, arg RepointDocumentFilesParams) error {
	_, err := q.db.Exec(ctx, repointDocumentFiles, arg.NewID, arg.OldID)
	return err
}

const repointImages = `-- name: RepointImages :exec
UPDATE documents.vehicle_image SET file_id = $1 WHERE file_id = $2
`

type RepointImagesParams struct {
	NewID pgtype.UUID
	OldID pgtype.UUID
}

func (q *Queries) RepointImages(ctx context.Context, arg RepointImagesParams) error {
	_, err := q.db.Exec(ctx, repointImages, arg.NewID, arg.OldID)
	return err
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :execrows
UPDATE documents.attachment SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAttachment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents.document SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteDocumentParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteFile = `-- name: SoftDeleteFile :execrows
UPDATE documents.file SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents.document SET doc_type = $2, nature = $3, title = $4, document_date = $5, issuer = $6, language = $7, note = $8, tags = $9,
    updated_by = $10, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $11 AND deleted_at IS NULL
RETURNING id, vehicle_id, doc_type, nature, title, document_date, issuer, language, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateDocumentParams struct {
	ID           pgtype.UUID
	DocType      string
	Nature       string
	Title        string
	DocumentDate pgtype.Date
	Issuer       pgtype.Text
	Language     pgtype.Text
	Note         string
	Tags         []string
	UpdatedBy    pgtype.UUID
	Version      int32
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (DocumentsDocument, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.DocType,
		arg.Nature,
		arg.Title,
		arg.DocumentDate,
		arg.Issuer,
		arg.Language,
		arg.Note,
		arg.Tags,
		arg.UpdatedBy,
		arg.Version,
	)
	var i DocumentsDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DocType,
		&i.Nature,
		&i.Title,
		&i.DocumentDate,
		&i.Issuer,
		&i.Language,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const upsertImage = `-- name: UpsertImage :one
INSERT INTO documents.vehicle_image (id, vehicle_id, file_id, is_primary, created_by) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (vehicle_id, file_id) DO UPDATE SET is_primary = EXCLUDED.is_primary
RETURNING id, vehicle_id, file_id, is_primary, created_at, created_by
`

type UpsertImageParams struct {
	ID        pgtype.UUID
	VehicleID pgtype.UUID
	FileID    pgtype.UUID
	IsPrimary bool
	CreatedBy pgtype.UUID
}

func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) (DocumentsVehicleImage, error) {
	row := q.db.QueryRow(ctx, upsertImage,
		arg.ID,
		arg.VehicleID,
		arg.FileID,
		arg.IsPrimary,
		arg.CreatedBy,
	)
	var i DocumentsVehicleImage
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.FileID,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
