// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oil.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntry = `-- name: GetEntry :one
SELECT id, vehicle_id, kind, occurred_at, time_zone, time_precision, odometer_reading_id, level_before_pct, level_before_input, level_after_pct, level_after_input, oil_added_ml, input_added, input_added_unit, oil_change_fill_ml, input_fill, input_fill_unit, oil_specification, oil_brand, oil_product, filter_changed, service_entry_id, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM oil.entry WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (OilEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i OilEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.LevelBeforePct,
		&i.LevelBeforeInput,
		&i.LevelAfterPct,
		&i.LevelAfterInput,
		&i.OilAddedMl,
		&i.InputAdded,
		&i.InputAddedUnit,
		&i.OilChangeFillMl,
		&i.InputFill,
		&i.InputFillUnit,
		&i.OilSpecification,
		&i.OilBrand,
		&i.OilProduct,
		&i.FilterChanged,
		&i.ServiceEntryID,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getEntryAny = `-- name: GetEntryAny :one
SELECT id, vehicle_id, kind, occurred_at, time_zone, time_precision, odometer_reading_id, level_before_pct, level_before_input, level_after_pct, level_after_input, oil_added_ml, input_added, input_added_unit, oil_change_fill_ml, input_fill, input_fill_unit, oil_specification, oil_brand, oil_product, filter_changed, service_entry_id, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM oil.entry WHERE id = $1
`

func (q *Queries) GetEntryAny(ctx context.Context, id pgtype.UUID) (OilEntry, error) {
	row := q.db.QueryRow(ctx, getEntryAny, id)
	var i OilEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.LevelBeforePct,
		&i.LevelBeforeInput,
		&i.LevelAfterPct,
		&i.LevelAfterInput,
		&i.OilAddedMl,
		&i.InputAdded,
		&i.InputAddedUnit,
		&i.OilChangeFillMl,
		&i.InputFill,
		&i.InputFillUnit,
		&i.OilSpecification,
		&i.OilBrand,
		&i.OilProduct,
		&i.FilterChanged,
		&i.ServiceEntryID,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO oil.entry (id, vehicle_id, kind, occurred_at, time_zone, time_precision, odometer_reading_id, level_before_pct,
    level_before_input, level_after_pct, level_after_input, oil_added_ml, input_added, input_added_unit, oil_change_fill_ml,
    input_fill, input_fill_unit, oil_specification, oil_brand, oil_product, filter_changed, service_entry_id, note, tags,
    confirmed_anomalies, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $27)
RETURNING id, vehicle_id, kind, occurred_at, time_zone, time_precision, odometer_reading_id, level_before_pct, level_before_input, level_after_pct, level_after_input, oil_added_ml, input_added, input_added_unit, oil_change_fill_ml, input_fill, input_fill_unit, oil_specification, oil_brand, oil_product, filter_changed, service_entry_id, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertEntryParams struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	Kind               string
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	OdometerReadingID  pgtype.UUID
	LevelBeforePct     pgtype.Numeric
	LevelBeforeInput   pgtype.Text
	LevelAfterPct      pgtype.Numeric
	LevelAfterInput    pgtype.Text
	OilAddedMl         pgtype.Int8
	InputAdded         pgtype.Numeric
	InputAddedUnit     pgtype.Text
	OilChangeFillMl    pgtype.Int8
	InputFill          pgtype.Numeric
	InputFillUnit      pgtype.Text
	OilSpecification   pgtype.Text
	OilBrand           pgtype.Text
	OilProduct         pgtype.Text
	FilterChanged      pgtype.Bool
	ServiceEntryID     pgtype.UUID
	Note               string
	Tags               []string
	ConfirmedAnomalies []byte
	Origin             string
	CreatedBy          pgtype.UUID
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (OilEntry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.ID,
		arg.VehicleID,
		arg.Kind,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.OdometerReadingID,
		arg.LevelBeforePct,
		arg.LevelBeforeInput,
		arg.LevelAfterPct,
		arg.LevelAfterInput,
		arg.OilAddedMl,
		arg.InputAdded,
		arg.InputAddedUnit,
		arg.OilChangeFillMl,
		arg.InputFill,
		arg.InputFillUnit,
		arg.OilSpecification,
		arg.OilBrand,
		arg.OilProduct,
		arg.FilterChanged,
		arg.ServiceEntryID,
		arg.Note,
		arg.Tags,
		arg.ConfirmedAnomalies,
		arg.Origin,
		arg.CreatedBy,
	)
	var i OilEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.LevelBeforePct,
		&i.LevelBeforeInput,
		&i.LevelAfterPct,
		&i.LevelAfterInput,
		&i.OilAddedMl,
		&i.InputAdded,
		&i.InputAddedUnit,
		&i.OilChangeFillMl,
		&i.InputFill,
		&i.InputFillUnit,
		&i.OilSpecification,
		&i.OilBrand,
		&i.OilProduct,
		&i.FilterChanged,
		&i.ServiceEntryID,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, vehicle_id, kind, occurred_at, time_zone, time_precision, odometer_reading_id, level_before_pct, level_before_input, level_after_pct, level_after_input, oil_added_ml, input_added, input_added_unit, oil_change_fill_ml, input_fill, input_fill_unit, oil_specification, oil_brand, oil_product, filter_changed, service_entry_id, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM oil.entry
WHERE vehicle_id = $1 AND ($2::boolean OR deleted_at IS NULL)
ORDER BY occurred_at, recorded_at, id
`

type ListEntriesParams struct {
	VehicleID      pgtype.UUID
	IncludeDeleted bool
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]OilEntry, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.VehicleID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OilEntry
	for rows.Next() {
		var i OilEntry
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Kind,
			&i.OccurredAt,
			&i.TimeZone,
			&i.TimePrecision,
			&i.OdometerReadingID,
			&i.LevelBeforePct,
			&i.LevelBeforeInput,
			&i.LevelAfterPct,
			&i.LevelAfterInput,
			&i.OilAddedMl,
			&i.InputAdded,
			&i.InputAddedUnit,
			&i.OilChangeFillMl,
			&i.InputFill,
			&i.InputFillUnit,
			&i.OilSpecification,
			&i.OilBrand,
			&i.OilProduct,
			&i.FilterChanged,
			&i.ServiceEntryID,
			&i.Note,
			&i.Tags,
			&i.ConfirmedAnomalies,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEntry = `-- name: SoftDeleteEntry :execrows
UPDATE oil.entry SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteEntryParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteEntry(ctx context.Context, arg SoftDeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEntry, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE oil.entry SET kind = $2, occurred_at = $3, time_zone = $4, time_precision = $5, odometer_reading_id = $6,
    level_before_pct = $7, level_before_input = $8, level_after_pct = $9, level_after_input = $10, oil_added_ml = $11,
    input_added = $12, input_added_unit = $13, oil_change_fill_ml = $14, input_fill = $15, input_fill_unit = $16,
    oil_specification = $17, oil_brand = $18, oil_product = $19, filter_changed = $20, service_entry_id = $21, note = $22,
    tags = $23, confirmed_anomalies = $24, updated_by = $25, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $26 AND deleted_at IS NULL
RETURNING id, vehicle_id, kind, occurred_at, time_zone, time_precision, odometer_reading_id, level_before_pct, level_before_input, level_after_pct, level_after_input, oil_added_ml, input_added, input_added_unit, oil_change_fill_ml, input_fill, input_fill_unit, oil_specification, oil_brand, oil_product, filter_changed, service_entry_id, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateEntryParams struct {
	ID                 pgtype.UUID
	Kind               string
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	OdometerReadingID  pgtype.UUID
	LevelBeforePct     pgtype.Numeric
	LevelBeforeInput   pgtype.Text
	LevelAfterPct      pgtype.Numeric
	LevelAfterInput    pgtype.Text
	OilAddedMl         pgtype.Int8
	InputAdded         pgtype.Numeric
	InputAddedUnit     pgtype.Text
	OilChangeFillMl    pgtype.Int8
	InputFill          pgtype.Numeric
	InputFillUnit      pgtype.Text
	OilSpecification   pgtype.Text
	OilBrand           pgtype.Text
	OilProduct         pgtype.Text
	FilterChanged      pgtype.Bool
	ServiceEntryID     pgtype.UUID
	Note               string
	Tags               []string
	ConfirmedAnomalies []byte
	UpdatedBy          pgtype.UUID
	Version            int32
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (OilEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Kind,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.OdometerReadingID,
		arg.LevelBeforePct,
		arg.LevelBeforeInput,
		arg.LevelAfterPct,
		arg.LevelAfterInput,
		arg.OilAddedMl,
		arg.InputAdded,
		arg.InputAddedUnit,
		arg.OilChangeFillMl,
		arg.InputFill,
		arg.InputFillUnit,
		arg.OilSpecification,
		arg.OilBrand,
		arg.OilProduct,
		arg.FilterChanged,
		arg.ServiceEntryID,
		arg.Note,
		arg.Tags,
		arg.ConfirmedAnomalies,
		arg.UpdatedBy,
		arg.Version,
	)
	var i OilEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.LevelBeforePct,
		&i.LevelBeforeInput,
		&i.LevelAfterPct,
		&i.LevelAfterInput,
		&i.OilAddedMl,
		&i.InputAdded,
		&i.InputAddedUnit,
		&i.OilChangeFillMl,
		&i.InputFill,
		&i.InputFillUnit,
		&i.OilSpecification,
		&i.OilBrand,
		&i.OilProduct,
		&i.FilterChanged,
		&i.ServiceEntryID,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
