// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: costs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmedOccurrences = `-- name: ConfirmedOccurrences :many
SELECT recurring_plan_id, plan_occurrence_on, id FROM costs.entry
WHERE vehicle_id = $1 AND recurring_plan_id IS NOT NULL AND deleted_at IS NULL
`

type ConfirmedOccurrencesRow struct {
	RecurringPlanID  pgtype.UUID
	PlanOccurrenceOn pgtype.Date
	ID               pgtype.UUID
}

func (q *Queries) ConfirmedOccurrences(ctx context.Context, vehicleID pgtype.UUID) ([]ConfirmedOccurrencesRow, error) {
	rows, err := q.db.Query(ctx, confirmedOccurrences, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfirmedOccurrencesRow
	for rows.Next() {
		var i ConfirmedOccurrencesRow
		if err := rows.Scan(&i.RecurringPlanID, &i.PlanOccurrenceOn, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLedgerSource = `-- name: DeleteLedgerSource :exec
DELETE FROM costs.ledger WHERE source_module = $1 AND source_id = $2
`

type DeleteLedgerSourceParams struct {
	SourceModule string
	SourceID     pgtype.UUID
}

func (q *Queries) DeleteLedgerSource(ctx context.Context, arg DeleteLedgerSourceParams) error {
	_, err := q.db.Exec(ctx, deleteLedgerSource, arg.SourceModule, arg.SourceID)
	return err
}

const entryForOccurrence = `-- name: EntryForOccurrence :one
SELECT id, vehicle_id, category, title, incurred_on, time_zone, covers_from, covers_to, amount_minor, currency, recurring_plan_id, plan_occurrence_on, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM costs.entry WHERE recurring_plan_id = $1 AND plan_occurrence_on = $2 AND deleted_at IS NULL
`

type EntryForOccurrenceParams struct {
	RecurringPlanID  pgtype.UUID
	PlanOccurrenceOn pgtype.Date
}

func (q *Queries) EntryForOccurrence(ctx context.Context, arg EntryForOccurrenceParams) (CostsEntry, error) {
	row := q.db.QueryRow(ctx, entryForOccurrence, arg.RecurringPlanID, arg.PlanOccurrenceOn)
	var i CostsEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.IncurredOn,
		&i.TimeZone,
		&i.CoversFrom,
		&i.CoversTo,
		&i.AmountMinor,
		&i.Currency,
		&i.RecurringPlanID,
		&i.PlanOccurrenceOn,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, vehicle_id, category, title, incurred_on, time_zone, covers_from, covers_to, amount_minor, currency, recurring_plan_id, plan_occurrence_on, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM costs.entry WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (CostsEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i CostsEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.IncurredOn,
		&i.TimeZone,
		&i.CoversFrom,
		&i.CoversTo,
		&i.AmountMinor,
		&i.Currency,
		&i.RecurringPlanID,
		&i.PlanOccurrenceOn,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, vehicle_id, category, title, amount_minor, currency, interval_months, interval_days, first_due_on, ends_on, remind_days_before, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM costs.plan WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id pgtype.UUID) (CostsPlan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i CostsPlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.FirstDueOn,
		&i.EndsOn,
		&i.RemindDaysBefore,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertDismissal = `-- name: InsertDismissal :execrows
INSERT INTO costs.occurrence_dismissal (plan_id, due_on, reason, created_by) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertDismissalParams struct {
	PlanID    pgtype.UUID
	DueOn     pgtype.Date
	Reason    string
	CreatedBy pgtype.UUID
}

func (q *Queries) InsertDismissal(ctx context.Context, arg InsertDismissalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDismissal,
		arg.PlanID,
		arg.DueOn,
		arg.Reason,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO costs.entry (id, vehicle_id, category, title, incurred_on, time_zone, covers_from, covers_to, amount_minor, currency,
    recurring_plan_id, plan_occurrence_on, note, tags, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $16)
RETURNING id, vehicle_id, category, title, incurred_on, time_zone, covers_from, covers_to, amount_minor, currency, recurring_plan_id, plan_occurrence_on, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertEntryParams struct {
	ID               pgtype.UUID
	VehicleID        pgtype.UUID
	Category         string
	Title            string
	IncurredOn       pgtype.Date
	TimeZone         string
	CoversFrom       pgtype.Date
	CoversTo         pgtype.Date
	AmountMinor      int64
	Currency         string
	RecurringPlanID  pgtype.UUID
	PlanOccurrenceOn pgtype.Date
	Note             string
	Tags             []string
	Origin           string
	CreatedBy        pgtype.UUID
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (CostsEntry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.ID,
		arg.VehicleID,
		arg.Category,
		arg.Title,
		arg.IncurredOn,
		arg.TimeZone,
		arg.CoversFrom,
		arg.CoversTo,
		arg.AmountMinor,
		arg.Currency,
		arg.RecurringPlanID,
		arg.PlanOccurrenceOn,
		arg.Note,
		arg.Tags,
		arg.Origin,
		arg.CreatedBy,
	)
	var i CostsEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.IncurredOn,
		&i.TimeZone,
		&i.CoversFrom,
		&i.CoversTo,
		&i.AmountMinor,
		&i.Currency,
		&i.RecurringPlanID,
		&i.PlanOccurrenceOn,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertLedger = `-- name: InsertLedger :exec
INSERT INTO costs.ledger (id, vehicle_id, source_module, source_id, category, cost_kind, booked_on, amount_minor, currency, covers_from, covers_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertLedgerParams struct {
	ID           pgtype.UUID
	VehicleID    pgtype.UUID
	SourceModule string
	SourceID     pgtype.UUID
	Category     string
	CostKind     pgtype.Text
	BookedOn     pgtype.Date
	AmountMinor  int64
	Currency     string
	CoversFrom   pgtype.Date
	CoversTo     pgtype.Date
}

func (q *Queries) InsertLedger(ctx context.Context, arg InsertLedgerParams) error {
	_, err := q.db.Exec(ctx, insertLedger,
		arg.ID,
		arg.VehicleID,
		arg.SourceModule,
		arg.SourceID,
		arg.Category,
		arg.CostKind,
		arg.BookedOn,
		arg.AmountMinor,
		arg.Currency,
		arg.CoversFrom,
		arg.CoversTo,
	)
	return err
}

const insertPlan = `-- name: InsertPlan :one
INSERT INTO costs.plan (id, vehicle_id, category, title, amount_minor, currency, interval_months, interval_days, first_due_on, ends_on,
    remind_days_before, active, note, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $15)
RETURNING id, vehicle_id, category, title, amount_minor, currency, interval_months, interval_days, first_due_on, ends_on, remind_days_before, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertPlanParams struct {
	ID               pgtype.UUID
	VehicleID        pgtype.UUID
	Category         string
	Title            string
	AmountMinor      int64
	Currency         string
	IntervalMonths   pgtype.Int4
	IntervalDays     pgtype.Int4
	FirstDueOn       pgtype.Date
	EndsOn           pgtype.Date
	RemindDaysBefore int32
	Active           bool
	Note             string
	Origin           string
	CreatedBy        pgtype.UUID
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (CostsPlan, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.ID,
		arg.VehicleID,
		arg.Category,
		arg.Title,
		arg.AmountMinor,
		arg.Currency,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.FirstDueOn,
		arg.EndsOn,
		arg.RemindDaysBefore,
		arg.Active,
		arg.Note,
		arg.Origin,
		arg.CreatedBy,
	)
	var i CostsPlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.FirstDueOn,
		&i.EndsOn,
		&i.RemindDaysBefore,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const isDismissed = `-- name: IsDismissed :one
SELECT count(*) FROM costs.occurrence_dismissal WHERE plan_id = $1 AND due_on = $2
`

type IsDismissedParams struct {
	PlanID pgtype.UUID
	DueOn  pgtype.Date
}

func (q *Queries) IsDismissed(ctx context.Context, arg IsDismissedParams) (int64, error) {
	row := q.db.QueryRow(ctx, isDismissed, arg.PlanID, arg.DueOn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDismissals = `-- name: ListDismissals :many
SELECT d.plan_id, d.due_on FROM costs.occurrence_dismissal d JOIN costs.plan p ON p.id = d.plan_id WHERE p.vehicle_id = $1
`

type ListDismissalsRow struct {
	PlanID pgtype.UUID
	DueOn  pgtype.Date
}

func (q *Queries) ListDismissals(ctx context.Context, vehicleID pgtype.UUID) ([]ListDismissalsRow, error) {
	rows, err := q.db.Query(ctx, listDismissals, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDismissalsRow
	for rows.Next() {
		var i ListDismissalsRow
		if err := rows.Scan(&i.PlanID, &i.DueOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, vehicle_id, category, title, incurred_on, time_zone, covers_from, covers_to, amount_minor, currency, recurring_plan_id, plan_occurrence_on, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM costs.entry
WHERE vehicle_id = $1
  AND ($2::boolean OR deleted_at IS NULL)
  AND ($3::date IS NULL OR incurred_on >= $3::date)
  AND ($4::date IS NULL OR incurred_on <= $4::date)
  AND ($5::text IS NULL OR category = $5::text)
  AND ($6::date IS NULL OR (incurred_on, id) < ($6::date, $7::uuid))
ORDER BY incurred_on DESC, id DESC
LIMIT $8
`

type ListEntriesParams struct {
	VehicleID      pgtype.UUID
	IncludeDeleted bool
	FromDate       pgtype.Date
	ToDate         pgtype.Date
	Category       pgtype.Text
	BeforeDate     pgtype.Date
	BeforeID       pgtype.UUID
	Lim            int32
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]CostsEntry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.VehicleID,
		arg.IncludeDeleted,
		arg.FromDate,
		arg.ToDate,
		arg.Category,
		arg.BeforeDate,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostsEntry
	for rows.Next() {
		var i CostsEntry
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Category,
			&i.Title,
			&i.IncurredOn,
			&i.TimeZone,
			&i.CoversFrom,
			&i.CoversTo,
			&i.AmountMinor,
			&i.Currency,
			&i.RecurringPlanID,
			&i.PlanOccurrenceOn,
			&i.Note,
			&i.Tags,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedger = `-- name: ListLedger :many
SELECT id, vehicle_id, source_module, source_id, category, cost_kind, booked_on, amount_minor, currency, covers_from, covers_to FROM costs.ledger WHERE vehicle_id = $1 ORDER BY booked_on, id
`

func (q *Queries) ListLedger(ctx context.Context, vehicleID pgtype.UUID) ([]CostsLedger, error) {
	rows, err := q.db.Query(ctx, listLedger, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostsLedger
	for rows.Next() {
		var i CostsLedger
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.SourceModule,
			&i.SourceID,
			&i.Category,
			&i.CostKind,
			&i.BookedOn,
			&i.AmountMinor,
			&i.Currency,
			&i.CoversFrom,
			&i.CoversTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, vehicle_id, category, title, amount_minor, currency, interval_months, interval_days, first_due_on, ends_on, remind_days_before, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM costs.plan
WHERE vehicle_id = $1 AND ($2::boolean OR deleted_at IS NULL)
ORDER BY title, id
`

type ListPlansParams struct {
	VehicleID      pgtype.UUID
	IncludeDeleted bool
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]CostsPlan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.VehicleID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostsPlan
	for rows.Next() {
		var i CostsPlan
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Category,
			&i.Title,
			&i.AmountMinor,
			&i.Currency,
			&i.IntervalMonths,
			&i.IntervalDays,
			&i.FirstDueOn,
			&i.EndsOn,
			&i.RemindDaysBefore,
			&i.Active,
			&i.Note,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEntry = `-- name: SoftDeleteEntry :execrows
UPDATE costs.entry SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteEntryParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteEntry(ctx context.Context, arg SoftDeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEntry, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePlan = `-- name: SoftDeletePlan :execrows
UPDATE costs.plan SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeletePlanParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlan, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE costs.entry SET category = $2, title = $3, incurred_on = $4, time_zone = $5, covers_from = $6, covers_to = $7,
    amount_minor = $8, currency = $9, note = $10, tags = $11, updated_by = $12, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $13 AND deleted_at IS NULL
RETURNING id, vehicle_id, category, title, incurred_on, time_zone, covers_from, covers_to, amount_minor, currency, recurring_plan_id, plan_occurrence_on, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateEntryParams struct {
	ID          pgtype.UUID
	Category    string
	Title       string
	IncurredOn  pgtype.Date
	TimeZone    string
	CoversFrom  pgtype.Date
	CoversTo    pgtype.Date
	AmountMinor int64
	Currency    string
	Note        string
	Tags        []string
	UpdatedBy   pgtype.UUID
	Version     int32
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (CostsEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Category,
		arg.Title,
		arg.IncurredOn,
		arg.TimeZone,
		arg.CoversFrom,
		arg.CoversTo,
		arg.AmountMinor,
		arg.Currency,
		arg.Note,
		arg.Tags,
		arg.UpdatedBy,
		arg.Version,
	)
	var i CostsEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.IncurredOn,
		&i.TimeZone,
		&i.CoversFrom,
		&i.CoversTo,
		&i.AmountMinor,
		&i.Currency,
		&i.RecurringPlanID,
		&i.PlanOccurrenceOn,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE costs.plan SET category = $2, title = $3, amount_minor = $4, currency = $5, interval_months = $6, interval_days = $7,
    first_due_on = $8, ends_on = $9, remind_days_before = $10, active = $11, note = $12, updated_by = $13, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $14 AND deleted_at IS NULL
RETURNING id, vehicle_id, category, title, amount_minor, currency, interval_months, interval_days, first_due_on, ends_on, remind_days_before, active, note, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdatePlanParams struct {
	ID               pgtype.UUID
	Category         string
	Title            string
	AmountMinor      int64
	Currency         string
	IntervalMonths   pgtype.Int4
	IntervalDays     pgtype.Int4
	FirstDueOn       pgtype.Date
	EndsOn           pgtype.Date
	RemindDaysBefore int32
	Active           bool
	Note             string
	UpdatedBy        pgtype.UUID
	Version          int32
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (CostsPlan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Category,
		arg.Title,
		arg.AmountMinor,
		arg.Currency,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.FirstDueOn,
		arg.EndsOn,
		arg.RemindDaysBefore,
		arg.Active,
		arg.Note,
		arg.UpdatedBy,
		arg.Version,
	)
	var i CostsPlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.FirstDueOn,
		&i.EndsOn,
		&i.RemindDaysBefore,
		&i.Active,
		&i.Note,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
