// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssistantConsent struct {
	AccountID pgtype.UUID
	Provider  string
	GivenAt   pgtype.Timestamptz
}

type AssistantConversation struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	VehicleID pgtype.UUID
	Title     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AssistantMessage struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Text           string
	ProposalIds    []pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type AssistantProposal struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	ConversationID pgtype.UUID
	VehicleID      pgtype.UUID
	Operation      string
	Summary        string
	Body           []byte
	Anomalies      []byte
	Status         string
	ExpiresAt      pgtype.Timestamptz
	ResultID       pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

type AssistantRequestLog struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	Provider     string
	Model        string
	InputTokens  int32
	OutputTokens int32
	Tools        []string
	CreatedAt    pgtype.Timestamptz
}

type AuditEvent struct {
	ID             pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	ActorAccountID pgtype.UUID
	ActorKind      string
	Action         string
	VehicleID      pgtype.UUID
	ObjectType     string
	ObjectID       pgtype.UUID
	Changes        []byte
	Reason         pgtype.Text
	RequestID      pgtype.Text
}

type CostsEntry struct {
	ID               pgtype.UUID
	VehicleID        pgtype.UUID
	Category         string
	Title            string
	IncurredOn       pgtype.Date
	TimeZone         string
	CoversFrom       pgtype.Date
	CoversTo         pgtype.Date
	AmountMinor      int64
	Currency         string
	RecurringPlanID  pgtype.UUID
	PlanOccurrenceOn pgtype.Date
	Note             string
	Tags             []string
	Origin           string
	CreatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
	UpdatedBy        pgtype.UUID
	RecordedAt       pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Version          int32
}

type CostsLedger struct {
	ID           pgtype.UUID
	VehicleID    pgtype.UUID
	SourceModule string
	SourceID     pgtype.UUID
	Category     string
	CostKind     pgtype.Text
	BookedOn     pgtype.Date
	AmountMinor  int64
	Currency     string
	CoversFrom   pgtype.Date
	CoversTo     pgtype.Date
}

type CostsOccurrenceDismissal struct {
	PlanID    pgtype.UUID
	DueOn     pgtype.Date
	Reason    string
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

type CostsPlan struct {
	ID               pgtype.UUID
	VehicleID        pgtype.UUID
	Category         string
	Title            string
	AmountMinor      int64
	Currency         string
	IntervalMonths   pgtype.Int4
	IntervalDays     pgtype.Int4
	FirstDueOn       pgtype.Date
	EndsOn           pgtype.Date
	RemindDaysBefore int32
	Active           bool
	Note             string
	Origin           string
	CreatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedAt        pgtype.Timestamptz
	UpdatedBy        pgtype.UUID
	RecordedAt       pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Version          int32
}

type DocumentsAttachment struct {
	ID         pgtype.UUID
	VehicleID  pgtype.UUID
	FileID     pgtype.UUID
	DocumentID pgtype.UUID
	TargetType string
	TargetID   pgtype.UUID
	Role       string
	Page       pgtype.Int4
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	DeletedAt  pgtype.Timestamptz
}

type DocumentsDocument struct {
	ID           pgtype.UUID
	VehicleID    pgtype.UUID
	DocType      string
	Nature       string
	Title        string
	DocumentDate pgtype.Date
	Issuer       pgtype.Text
	Language     pgtype.Text
	Note         string
	Tags         []string
	Origin       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	RecordedAt   pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int32
}

type DocumentsDocumentFile struct {
	DocumentID pgtype.UUID
	Position   int32
	FileID     pgtype.UUID
}

type DocumentsFile struct {
	ID               pgtype.UUID
	VehicleID        pgtype.UUID
	StorageKey       string
	OriginalName     string
	MediaType        string
	SizeBytes        int64
	Sha256           string
	ReceivedAt       pgtype.Timestamptz
	CapturedAtClient pgtype.Timestamptz
	CaptureSource    pgtype.Text
	Derivatives      []string
	HasLocation      bool
	SupersedesID     pgtype.UUID
	ReplaceReason    pgtype.Text
	UploadTimeOrigin string
	CreatedBy        pgtype.UUID
	DeletedAt        pgtype.Timestamptz
}

type DocumentsVehicleImage struct {
	ID        pgtype.UUID
	VehicleID pgtype.UUID
	FileID    pgtype.UUID
	IsPrimary bool
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

type FuelFill struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	EnergyCarrier      string
	Quantity           int64
	InputQuantity      pgtype.Numeric
	InputUnit          string
	FillLevel          string
	PreviousMissed     bool
	OdometerReadingID  pgtype.UUID
	CostAmountMinor    pgtype.Int8
	CostCurrency       pgtype.Text
	InputPricePerUnit  pgtype.Numeric
	InputPriceCurrency pgtype.Text
	InputPriceUnit     pgtype.Text
	SocStartPct        pgtype.Numeric
	SocEndPct          pgtype.Numeric
	ChargeType         pgtype.Text
	Station            pgtype.Text
	Note               string
	Tags               []string
	ConfirmedAnomalies []byte
	Origin             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
	RecordedAt         pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Version            int32
}

type IdentityAccount struct {
	ID            pgtype.UUID
	Email         string
	EmailVerified bool
	DisplayName   string
	Status        string
	IsAdmin       bool
	PasswordHash  pgtype.Text
	Settings      []byte
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
}

type IdentityApiToken struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	Name       string
	TokenHash  []byte
	Scopes     []string
	VehicleIds []pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type IdentitySession struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	TokenHash         []byte
	CsrfToken         string
	ClientKind        string
	UserAgent         string
	CreatedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type IdentityVehicleMembership struct {
	VehicleID pgtype.UUID
	AccountID pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type MaintenanceCompletion struct {
	ID             pgtype.UUID
	ItemID         pgtype.UUID
	VehicleID      pgtype.UUID
	ServiceEntryID pgtype.UUID
	Kind           string
	CompletedOn    pgtype.Date
	CompletedTotal pgtype.Int8
	Reason         pgtype.Text
	IdempotencyKey pgtype.Text
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
}

type MaintenanceItem struct {
	ID                      pgtype.UUID
	VehicleID               pgtype.UUID
	Title                   string
	Description             pgtype.Text
	Category                string
	ManufacturerRecommended bool
	SourceDocumentID        pgtype.UUID
	SourcePage              pgtype.Int4
	ScheduleMode            string
	IntervalMonths          pgtype.Int4
	IntervalDays            pgtype.Int4
	IntervalDistance        pgtype.Int8
	AnchorDate              pgtype.Date
	AnchorTotal             pgtype.Int8
	DueDateOnce             pgtype.Date
	DueTotalOnce            pgtype.Int8
	UpcomingDays            pgtype.Int4
	DueDays                 pgtype.Int4
	UpcomingDistance        pgtype.Int8
	DueDistance             pgtype.Int8
	DistanceUnit            string
	Active                  bool
	Note                    string
	Origin                  string
	CreatedAt               pgtype.Timestamptz
	CreatedBy               pgtype.UUID
	UpdatedAt               pgtype.Timestamptz
	UpdatedBy               pgtype.UUID
	RecordedAt              pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	Version                 int32
}

type OdometerReading struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	Value              int64
	InputValue         pgtype.Numeric
	InputUnit          string
	Source             string
	SourceRef          pgtype.UUID
	Status             string
	ConfirmedAnomalies []byte
	SupersedesID       pgtype.UUID
	PhotoFileID        pgtype.UUID
	Note               string
	Origin             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	RecordedAt         pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Version            int32
}

type OdometerSegment struct {
	ID              pgtype.UUID
	VehicleID       pgtype.UUID
	SequenceNo      int32
	StartedAt       pgtype.Timestamptz
	TimeZone        string
	StartMeterValue int64
	Offset          int64
	Reason          string
	Note            string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
}

type OilEntry struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	Kind               string
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	OdometerReadingID  pgtype.UUID
	LevelBeforePct     pgtype.Numeric
	LevelBeforeInput   pgtype.Text
	LevelAfterPct      pgtype.Numeric
	LevelAfterInput    pgtype.Text
	OilAddedMl         pgtype.Int8
	InputAdded         pgtype.Numeric
	InputAddedUnit     pgtype.Text
	OilChangeFillMl    pgtype.Int8
	InputFill          pgtype.Numeric
	InputFillUnit      pgtype.Text
	OilSpecification   pgtype.Text
	OilBrand           pgtype.Text
	OilProduct         pgtype.Text
	FilterChanged      pgtype.Bool
	ServiceEntryID     pgtype.UUID
	Note               string
	Tags               []string
	ConfirmedAnomalies []byte
	Origin             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
	RecordedAt         pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Version            int32
}

type ServiceCostItem struct {
	ID          pgtype.UUID
	EntryID     pgtype.UUID
	Position    int32
	Kind        string
	Label       pgtype.Text
	AmountMinor int64
}

type ServiceEntry struct {
	ID                pgtype.UUID
	VehicleID         pgtype.UUID
	Kind              string
	Category          pgtype.Text
	Title             string
	Description       pgtype.Text
	OccurredAt        pgtype.Timestamptz
	TimeZone          string
	TimePrecision     string
	OdometerReadingID pgtype.UUID
	Currency          string
	ProviderName      pgtype.Text
	InvoiceNumber     pgtype.Text
	CostUnknown       bool
	Note              string
	Tags              []string
	Origin            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	RecordedAt        pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	Version           int32
}

type ServicePartLine struct {
	ID             pgtype.UUID
	EntryID        pgtype.UUID
	Position       int32
	Name           string
	PartNumber     pgtype.Text
	Quantity       pgtype.Numeric
	QuantityUnit   pgtype.Text
	UnitPriceMinor pgtype.Int8
	CostItemID     pgtype.UUID
}

type TripsCategory struct {
	ID              pgtype.UUID
	VehicleID       pgtype.UUID
	Name            string
	Kind            string
	PurposeRequired bool
	Active          bool
	DefaultKey      pgtype.Text
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	Version         int32
}

type TripsTrip struct {
	ID              pgtype.UUID
	RootID          pgtype.UUID
	VehicleID       pgtype.UUID
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	TimeZone        string
	StartReadingID  pgtype.UUID
	EndReadingID    pgtype.UUID
	StartLocation   pgtype.Text
	EndLocation     pgtype.Text
	Purpose         pgtype.Text
	CategoryID      pgtype.UUID
	DriverAccountID pgtype.UUID
	Note            string
	Status          string
	SupersedesID    pgtype.UUID
	ChangeReason    pgtype.Text
	Origin          string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	RecordedAt      pgtype.Timestamptz
	Version         int32
}

type VehiclesVehicle struct {
	ID                pgtype.UUID
	DisplayName       string
	Vin               pgtype.Text
	LicensePlate      pgtype.Text
	PlateCountry      pgtype.Text
	Make              pgtype.Text
	Model             pgtype.Text
	Variant           pgtype.Text
	ModelYear         pgtype.Int4
	FirstRegistration pgtype.Date
	BodyType          string
	EngineCode        pgtype.Text
	DisplacementCcm   pgtype.Int4
	PowerKw           pgtype.Int4
	Transmission      pgtype.Text
	UsageMeter        string
	EnergyCarriers    []string
	OdometerRequired  bool
	OwnerTimeZone     string
	DefaultCurrency   string
	Status            string
	PurchaseDate      pgtype.Date
	PurchaseAmount    pgtype.Int8
	PurchaseCurrency  pgtype.Text
	SaleDate          pgtype.Date
	SaleAmount        pgtype.Int8
	SaleCurrency      pgtype.Text
	Note              string
	Tags              []string
	Extra             []byte
	Origin            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	RecordedAt        pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	Version           int32
}
