// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: service.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCostItems = `-- name: DeleteCostItems :exec
DELETE FROM service.cost_item WHERE entry_id = $1
`

func (q *Queries) DeleteCostItems(ctx context.Context, entryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCostItems, entryID)
	return err
}

const deletePartLines = `-- name: DeletePartLines :exec
DELETE FROM service.part_line WHERE entry_id = $1
`

func (q *Queries) DeletePartLines(ctx context.Context, entryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePartLines, entryID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, vehicle_id, kind, category, title, description, occurred_at, time_zone, time_precision, odometer_reading_id, currency, provider_name, invoice_number, cost_unknown, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM service.entry WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (ServiceEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i ServiceEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.Currency,
		&i.ProviderName,
		&i.InvoiceNumber,
		&i.CostUnknown,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertCostItem = `-- name: InsertCostItem :exec
INSERT INTO service.cost_item (id, entry_id, position, kind, label, amount_minor) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCostItemParams struct {
	ID          pgtype.UUID
	EntryID     pgtype.UUID
	Position    int32
	Kind        string
	Label       pgtype.Text
	AmountMinor int64
}

func (q *Queries) InsertCostItem(ctx context.Context, arg InsertCostItemParams) error {
	_, err := q.db.Exec(ctx, insertCostItem,
		arg.ID,
		arg.EntryID,
		arg.Position,
		arg.Kind,
		arg.Label,
		arg.AmountMinor,
	)
	return err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO service.entry (id, vehicle_id, kind, category, title, description, occurred_at, time_zone, time_precision, odometer_reading_id,
    currency, provider_name, invoice_number, cost_unknown, note, tags, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $18)
RETURNING id, vehicle_id, kind, category, title, description, occurred_at, time_zone, time_precision, odometer_reading_id, currency, provider_name, invoice_number, cost_unknown, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertEntryParams struct {
	ID                pgtype.UUID
	VehicleID         pgtype.UUID
	Kind              string
	Category          pgtype.Text
	Title             string
	Description       pgtype.Text
	OccurredAt        pgtype.Timestamptz
	TimeZone          string
	TimePrecision     string
	OdometerReadingID pgtype.UUID
	Currency          string
	ProviderName      pgtype.Text
	InvoiceNumber     pgtype.Text
	CostUnknown       bool
	Note              string
	Tags              []string
	Origin            string
	CreatedBy         pgtype.UUID
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (ServiceEntry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.ID,
		arg.VehicleID,
		arg.Kind,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.OdometerReadingID,
		arg.Currency,
		arg.ProviderName,
		arg.InvoiceNumber,
		arg.CostUnknown,
		arg.Note,
		arg.Tags,
		arg.Origin,
		arg.CreatedBy,
	)
	var i ServiceEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.Currency,
		&i.ProviderName,
		&i.InvoiceNumber,
		&i.CostUnknown,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertPartLine = `-- name: InsertPartLine :exec
INSERT INTO service.part_line (id, entry_id, position, name, part_number, quantity, quantity_unit, unit_price_minor, cost_item_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPartLineParams struct {
	ID             pgtype.UUID
	EntryID        pgtype.UUID
	Position       int32
	Name           string
	PartNumber     pgtype.Text
	Quantity       pgtype.Numeric
	QuantityUnit   pgtype.Text
	UnitPriceMinor pgtype.Int8
	CostItemID     pgtype.UUID
}

func (q *Queries) InsertPartLine(ctx context.Context, arg InsertPartLineParams) error {
	_, err := q.db.Exec(ctx, insertPartLine,
		arg.ID,
		arg.EntryID,
		arg.Position,
		arg.Name,
		arg.PartNumber,
		arg.Quantity,
		arg.QuantityUnit,
		arg.UnitPriceMinor,
		arg.CostItemID,
	)
	return err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT id, vehicle_id, kind, category, title, description, occurred_at, time_zone, time_precision, odometer_reading_id, currency, provider_name, invoice_number, cost_unknown, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM service.entry WHERE vehicle_id = $1 AND deleted_at IS NULL ORDER BY occurred_at, id
`

func (q *Queries) ListAllEntries(ctx context.Context, vehicleID pgtype.UUID) ([]ServiceEntry, error) {
	rows, err := q.db.Query(ctx, listAllEntries, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceEntry
	for rows.Next() {
		var i ServiceEntry
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Kind,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.OccurredAt,
			&i.TimeZone,
			&i.TimePrecision,
			&i.OdometerReadingID,
			&i.Currency,
			&i.ProviderName,
			&i.InvoiceNumber,
			&i.CostUnknown,
			&i.Note,
			&i.Tags,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostItems = `-- name: ListCostItems :many
SELECT id, entry_id, position, kind, label, amount_minor FROM service.cost_item WHERE entry_id = ANY($1::uuid[]) ORDER BY entry_id, position
`

func (q *Queries) ListCostItems(ctx context.Context, ids []pgtype.UUID) ([]ServiceCostItem, error) {
	rows, err := q.db.Query(ctx, listCostItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCostItem
	for rows.Next() {
		var i ServiceCostItem
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Position,
			&i.Kind,
			&i.Label,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, vehicle_id, kind, category, title, description, occurred_at, time_zone, time_precision, odometer_reading_id, currency, provider_name, invoice_number, cost_unknown, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM service.entry e
WHERE e.vehicle_id = $1
  AND ($2::boolean OR e.deleted_at IS NULL)
  AND ($3::timestamptz IS NULL OR e.occurred_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR e.occurred_at < $4::timestamptz)
  AND ($5::text IS NULL OR e.kind = $5::text)
  AND ($6::text IS NULL OR e.title ILIKE '%' || $6::text || '%' OR e.description ILIKE '%' || $6::text || '%'
       OR e.provider_name ILIKE '%' || $6::text || '%' OR e.invoice_number ILIKE '%' || $6::text || '%'
       OR EXISTS (SELECT 1 FROM service.part_line p WHERE p.entry_id = e.id
                  AND (p.name ILIKE '%' || $6::text || '%' OR p.part_number ILIKE '%' || $6::text || '%')))
  AND ($7::timestamptz IS NULL OR (e.occurred_at, e.id) < ($7::timestamptz, $8::uuid))
ORDER BY e.occurred_at DESC, e.id DESC
LIMIT $9
`

type ListEntriesParams struct {
	VehicleID      pgtype.UUID
	IncludeDeleted bool
	FromTs         pgtype.Timestamptz
	ToTs           pgtype.Timestamptz
	Kind           pgtype.Text
	Q              pgtype.Text
	BeforeTs       pgtype.Timestamptz
	BeforeID       pgtype.UUID
	Lim            int32
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ServiceEntry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.VehicleID,
		arg.IncludeDeleted,
		arg.FromTs,
		arg.ToTs,
		arg.Kind,
		arg.Q,
		arg.BeforeTs,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceEntry
	for rows.Next() {
		var i ServiceEntry
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Kind,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.OccurredAt,
			&i.TimeZone,
			&i.TimePrecision,
			&i.OdometerReadingID,
			&i.Currency,
			&i.ProviderName,
			&i.InvoiceNumber,
			&i.CostUnknown,
			&i.Note,
			&i.Tags,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartLines = `-- name: ListPartLines :many
SELECT id, entry_id, position, name, part_number, quantity, quantity_unit, unit_price_minor, cost_item_id FROM service.part_line WHERE entry_id = ANY($1::uuid[]) ORDER BY entry_id, position
`

func (q *Queries) ListPartLines(ctx context.Context, ids []pgtype.UUID) ([]ServicePartLine, error) {
	rows, err := q.db.Query(ctx, listPartLines, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicePartLine
	for rows.Next() {
		var i ServicePartLine
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Position,
			&i.Name,
			&i.PartNumber,
			&i.Quantity,
			&i.QuantityUnit,
			&i.UnitPriceMinor,
			&i.CostItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEntry = `-- name: SoftDeleteEntry :execrows
UPDATE service.entry SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteEntryParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteEntry(ctx context.Context, arg SoftDeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteEntry, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE service.entry SET kind = $2, category = $3, title = $4, description = $5, occurred_at = $6, time_zone = $7, time_precision = $8,
    odometer_reading_id = $9, currency = $10, provider_name = $11, invoice_number = $12, cost_unknown = $13, note = $14, tags = $15,
    updated_by = $16, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $17 AND deleted_at IS NULL
RETURNING id, vehicle_id, kind, category, title, description, occurred_at, time_zone, time_precision, odometer_reading_id, currency, provider_name, invoice_number, cost_unknown, note, tags, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateEntryParams struct {
	ID                pgtype.UUID
	Kind              string
	Category          pgtype.Text
	Title             string
	Description       pgtype.Text
	OccurredAt        pgtype.Timestamptz
	TimeZone          string
	TimePrecision     string
	OdometerReadingID pgtype.UUID
	Currency          string
	ProviderName      pgtype.Text
	InvoiceNumber     pgtype.Text
	CostUnknown       bool
	Note              string
	Tags              []string
	UpdatedBy         pgtype.UUID
	Version           int32
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (ServiceEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Kind,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.OdometerReadingID,
		arg.Currency,
		arg.ProviderName,
		arg.InvoiceNumber,
		arg.CostUnknown,
		arg.Note,
		arg.Tags,
		arg.UpdatedBy,
		arg.Version,
	)
	var i ServiceEntry
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.OdometerReadingID,
		&i.Currency,
		&i.ProviderName,
		&i.InvoiceNumber,
		&i.CostUnknown,
		&i.Note,
		&i.Tags,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
