// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vehicles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVehicle = `-- name: GetVehicle :one
SELECT id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM vehicles.vehicle WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVehicle(ctx context.Context, id pgtype.UUID) (VehiclesVehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i VehiclesVehicle
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateCountry,
		&i.Make,
		&i.Model,
		&i.Variant,
		&i.ModelYear,
		&i.FirstRegistration,
		&i.BodyType,
		&i.EngineCode,
		&i.DisplacementCcm,
		&i.PowerKw,
		&i.Transmission,
		&i.UsageMeter,
		&i.EnergyCarriers,
		&i.OdometerRequired,
		&i.OwnerTimeZone,
		&i.DefaultCurrency,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseAmount,
		&i.PurchaseCurrency,
		&i.SaleDate,
		&i.SaleAmount,
		&i.SaleCurrency,
		&i.Note,
		&i.Tags,
		&i.Extra,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getVehicleIncludingDeleted = `-- name: GetVehicleIncludingDeleted :one
SELECT id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM vehicles.vehicle WHERE id = $1
`

func (q *Queries) GetVehicleIncludingDeleted(ctx context.Context, id pgtype.UUID) (VehiclesVehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleIncludingDeleted, id)
	var i VehiclesVehicle
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateCountry,
		&i.Make,
		&i.Model,
		&i.Variant,
		&i.ModelYear,
		&i.FirstRegistration,
		&i.BodyType,
		&i.EngineCode,
		&i.DisplacementCcm,
		&i.PowerKw,
		&i.Transmission,
		&i.UsageMeter,
		&i.EnergyCarriers,
		&i.OdometerRequired,
		&i.OwnerTimeZone,
		&i.DefaultCurrency,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseAmount,
		&i.PurchaseCurrency,
		&i.SaleDate,
		&i.SaleAmount,
		&i.SaleCurrency,
		&i.Note,
		&i.Tags,
		&i.Extra,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit.event (id, actor_account_id, actor_kind, action, vehicle_id, object_type, object_id, changes, reason, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditParams struct {
	ID             pgtype.UUID
	ActorAccountID pgtype.UUID
	ActorKind      string
	Action         string
	VehicleID      pgtype.UUID
	ObjectType     string
	ObjectID       pgtype.UUID
	Changes        []byte
	Reason         pgtype.Text
	RequestID      pgtype.Text
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ID,
		arg.ActorAccountID,
		arg.ActorKind,
		arg.Action,
		arg.VehicleID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Changes,
		arg.Reason,
		arg.RequestID,
	)
	return err
}

const insertVehicle = `-- name: InsertVehicle :one
INSERT INTO vehicles.vehicle (
    id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration,
    body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required,
    owner_time_zone, default_currency, purchase_date, purchase_amount, purchase_currency, note, tags, extra,
    origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $28)
RETURNING id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertVehicleParams struct {
	ID                pgtype.UUID
	DisplayName       string
	Vin               pgtype.Text
	LicensePlate      pgtype.Text
	PlateCountry      pgtype.Text
	Make              pgtype.Text
	Model             pgtype.Text
	Variant           pgtype.Text
	ModelYear         pgtype.Int4
	FirstRegistration pgtype.Date
	BodyType          string
	EngineCode        pgtype.Text
	DisplacementCcm   pgtype.Int4
	PowerKw           pgtype.Int4
	Transmission      pgtype.Text
	UsageMeter        string
	EnergyCarriers    []string
	OdometerRequired  bool
	OwnerTimeZone     string
	DefaultCurrency   string
	PurchaseDate      pgtype.Date
	PurchaseAmount    pgtype.Int8
	PurchaseCurrency  pgtype.Text
	Note              string
	Tags              []string
	Extra             []byte
	Origin            string
	CreatedBy         pgtype.UUID
}

func (q *Queries) InsertVehicle(ctx context.Context, arg InsertVehicleParams) (VehiclesVehicle, error) {
	row := q.db.QueryRow(ctx, insertVehicle,
		arg.ID,
		arg.DisplayName,
		arg.Vin,
		arg.LicensePlate,
		arg.PlateCountry,
		arg.Make,
		arg.Model,
		arg.Variant,
		arg.ModelYear,
		arg.FirstRegistration,
		arg.BodyType,
		arg.EngineCode,
		arg.DisplacementCcm,
		arg.PowerKw,
		arg.Transmission,
		arg.UsageMeter,
		arg.EnergyCarriers,
		arg.OdometerRequired,
		arg.OwnerTimeZone,
		arg.DefaultCurrency,
		arg.PurchaseDate,
		arg.PurchaseAmount,
		arg.PurchaseCurrency,
		arg.Note,
		arg.Tags,
		arg.Extra,
		arg.Origin,
		arg.CreatedBy,
	)
	var i VehiclesVehicle
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateCountry,
		&i.Make,
		&i.Model,
		&i.Variant,
		&i.ModelYear,
		&i.FirstRegistration,
		&i.BodyType,
		&i.EngineCode,
		&i.DisplacementCcm,
		&i.PowerKw,
		&i.Transmission,
		&i.UsageMeter,
		&i.EnergyCarriers,
		&i.OdometerRequired,
		&i.OwnerTimeZone,
		&i.DefaultCurrency,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseAmount,
		&i.PurchaseCurrency,
		&i.SaleDate,
		&i.SaleAmount,
		&i.SaleCurrency,
		&i.Note,
		&i.Tags,
		&i.Extra,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor_account_id, actor_kind, action, vehicle_id, object_type, object_id, changes, reason, request_id FROM audit.event
WHERE vehicle_id = $1
  AND ($2::uuid IS NULL OR object_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR (occurred_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $5
`

type ListAuditEventsParams struct {
	VehicleID pgtype.UUID
	ObjectID  pgtype.UUID
	BeforeTs  pgtype.Timestamptz
	BeforeID  pgtype.UUID
	Lim       int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.VehicleID,
		arg.ObjectID,
		arg.BeforeTs,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorAccountID,
			&i.ActorKind,
			&i.Action,
			&i.VehicleID,
			&i.ObjectType,
			&i.ObjectID,
			&i.Changes,
			&i.Reason,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM vehicles.vehicle
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR (display_name, id) > ($3::text, $4::uuid))
ORDER BY display_name, id
LIMIT $5
`

type ListVehiclesParams struct {
	Ids       []pgtype.UUID
	Status    pgtype.Text
	AfterName pgtype.Text
	AfterID   pgtype.UUID
	Lim       int32
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]VehiclesVehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles,
		arg.Ids,
		arg.Status,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehiclesVehicle
	for rows.Next() {
		var i VehiclesVehicle
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Vin,
			&i.LicensePlate,
			&i.PlateCountry,
			&i.Make,
			&i.Model,
			&i.Variant,
			&i.ModelYear,
			&i.FirstRegistration,
			&i.BodyType,
			&i.EngineCode,
			&i.DisplacementCcm,
			&i.PowerKw,
			&i.Transmission,
			&i.UsageMeter,
			&i.EnergyCarriers,
			&i.OdometerRequired,
			&i.OwnerTimeZone,
			&i.DefaultCurrency,
			&i.Status,
			&i.PurchaseDate,
			&i.PurchaseAmount,
			&i.PurchaseCurrency,
			&i.SaleDate,
			&i.SaleAmount,
			&i.SaleCurrency,
			&i.Note,
			&i.Tags,
			&i.Extra,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVehicle = `-- name: LockVehicle :one
SELECT id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM vehicles.vehicle WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockVehicle(ctx context.Context, id pgtype.UUID) (VehiclesVehicle, error) {
	row := q.db.QueryRow(ctx, lockVehicle, id)
	var i VehiclesVehicle
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateCountry,
		&i.Make,
		&i.Model,
		&i.Variant,
		&i.ModelYear,
		&i.FirstRegistration,
		&i.BodyType,
		&i.EngineCode,
		&i.DisplacementCcm,
		&i.PowerKw,
		&i.Transmission,
		&i.UsageMeter,
		&i.EnergyCarriers,
		&i.OdometerRequired,
		&i.OwnerTimeZone,
		&i.DefaultCurrency,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseAmount,
		&i.PurchaseCurrency,
		&i.SaleDate,
		&i.SaleAmount,
		&i.SaleCurrency,
		&i.Note,
		&i.Tags,
		&i.Extra,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const restoreVehicle = `-- name: RestoreVehicle :one
UPDATE vehicles.vehicle SET deleted_at = NULL, updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NOT NULL AND deleted_at > now() - interval '30 days'
RETURNING id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type RestoreVehicleParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) RestoreVehicle(ctx context.Context, arg RestoreVehicleParams) (VehiclesVehicle, error) {
	row := q.db.QueryRow(ctx, restoreVehicle, arg.ID, arg.UpdatedBy)
	var i VehiclesVehicle
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateCountry,
		&i.Make,
		&i.Model,
		&i.Variant,
		&i.ModelYear,
		&i.FirstRegistration,
		&i.BodyType,
		&i.EngineCode,
		&i.DisplacementCcm,
		&i.PowerKw,
		&i.Transmission,
		&i.UsageMeter,
		&i.EnergyCarriers,
		&i.OdometerRequired,
		&i.OwnerTimeZone,
		&i.DefaultCurrency,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseAmount,
		&i.PurchaseCurrency,
		&i.SaleDate,
		&i.SaleAmount,
		&i.SaleCurrency,
		&i.Note,
		&i.Tags,
		&i.Extra,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const softDeleteVehicle = `-- name: SoftDeleteVehicle :execrows
UPDATE vehicles.vehicle SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteVehicleParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteVehicle(ctx context.Context, arg SoftDeleteVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteVehicle, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles.vehicle SET
    display_name = $2, vin = $3, license_plate = $4, plate_country = $5, make = $6, model = $7, variant = $8,
    model_year = $9, first_registration = $10, body_type = $11, engine_code = $12, displacement_ccm = $13,
    power_kw = $14, transmission = $15, usage_meter = $16, energy_carriers = $17, odometer_required = $18,
    owner_time_zone = $19, default_currency = $20, status = $21, purchase_date = $22, purchase_amount = $23,
    purchase_currency = $24, sale_date = $25, sale_amount = $26, sale_currency = $27, note = $28, tags = $29,
    extra = $30, updated_by = $31, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $32 AND deleted_at IS NULL
RETURNING id, display_name, vin, license_plate, plate_country, make, model, variant, model_year, first_registration, body_type, engine_code, displacement_ccm, power_kw, transmission, usage_meter, energy_carriers, odometer_required, owner_time_zone, default_currency, status, purchase_date, purchase_amount, purchase_currency, sale_date, sale_amount, sale_currency, note, tags, extra, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateVehicleParams struct {
	ID                pgtype.UUID
	DisplayName       string
	Vin               pgtype.Text
	LicensePlate      pgtype.Text
	PlateCountry      pgtype.Text
	Make              pgtype.Text
	Model             pgtype.Text
	Variant           pgtype.Text
	ModelYear         pgtype.Int4
	FirstRegistration pgtype.Date
	BodyType          string
	EngineCode        pgtype.Text
	DisplacementCcm   pgtype.Int4
	PowerKw           pgtype.Int4
	Transmission      pgtype.Text
	UsageMeter        string
	EnergyCarriers    []string
	OdometerRequired  bool
	OwnerTimeZone     string
	DefaultCurrency   string
	Status            string
	PurchaseDate      pgtype.Date
	PurchaseAmount    pgtype.Int8
	PurchaseCurrency  pgtype.Text
	SaleDate          pgtype.Date
	SaleAmount        pgtype.Int8
	SaleCurrency      pgtype.Text
	Note              string
	Tags              []string
	Extra             []byte
	UpdatedBy         pgtype.UUID
	Version           int32
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (VehiclesVehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.DisplayName,
		arg.Vin,
		arg.LicensePlate,
		arg.PlateCountry,
		arg.Make,
		arg.Model,
		arg.Variant,
		arg.ModelYear,
		arg.FirstRegistration,
		arg.BodyType,
		arg.EngineCode,
		arg.DisplacementCcm,
		arg.PowerKw,
		arg.Transmission,
		arg.UsageMeter,
		arg.EnergyCarriers,
		arg.OdometerRequired,
		arg.OwnerTimeZone,
		arg.DefaultCurrency,
		arg.Status,
		arg.PurchaseDate,
		arg.PurchaseAmount,
		arg.PurchaseCurrency,
		arg.SaleDate,
		arg.SaleAmount,
		arg.SaleCurrency,
		arg.Note,
		arg.Tags,
		arg.Extra,
		arg.UpdatedBy,
		arg.Version,
	)
	var i VehiclesVehicle
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Vin,
		&i.LicensePlate,
		&i.PlateCountry,
		&i.Make,
		&i.Model,
		&i.Variant,
		&i.ModelYear,
		&i.FirstRegistration,
		&i.BodyType,
		&i.EngineCode,
		&i.DisplacementCcm,
		&i.PowerKw,
		&i.Transmission,
		&i.UsageMeter,
		&i.EnergyCarriers,
		&i.OdometerRequired,
		&i.OwnerTimeZone,
		&i.DefaultCurrency,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseAmount,
		&i.PurchaseCurrency,
		&i.SaleDate,
		&i.SaleAmount,
		&i.SaleCurrency,
		&i.Note,
		&i.Tags,
		&i.Extra,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const vehiclesWithVIN = `-- name: VehiclesWithVIN :many
SELECT id, display_name FROM vehicles.vehicle
WHERE vin = $1 AND id <> $2 AND id = ANY($3::uuid[]) AND deleted_at IS NULL
`

type VehiclesWithVINParams struct {
	Vin pgtype.Text
	ID  pgtype.UUID
	Ids []pgtype.UUID
}

type VehiclesWithVINRow struct {
	ID          pgtype.UUID
	DisplayName string
}

func (q *Queries) VehiclesWithVIN(ctx context.Context, arg VehiclesWithVINParams) ([]VehiclesWithVINRow, error) {
	rows, err := q.db.Query(ctx, vehiclesWithVIN, arg.Vin, arg.ID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehiclesWithVINRow
	for rows.Next() {
		var i VehiclesWithVINRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
