// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assistant.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRequestsSince = `-- name: CountRequestsSince :one
SELECT count(*) FROM assistant.request_log WHERE account_id = $1 AND created_at >= $2
`

type CountRequestsSinceParams struct {
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountRequestsSince(ctx context.Context, arg CountRequestsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsSince, arg.AccountID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideProposal = `-- name: DecideProposal :one
UPDATE assistant.proposal SET status = $2, result_id = $3, anomalies = $4, body = $5, decided_at = now() WHERE id = $1 RETURNING id, account_id, conversation_id, vehicle_id, operation, summary, body, anomalies, status, expires_at, result_id, created_at, decided_at
`

type DecideProposalParams struct {
	ID        pgtype.UUID
	Status    string
	ResultID  pgtype.UUID
	Anomalies []byte
	Body      []byte
}

func (q *Queries) DecideProposal(ctx context.Context, arg DecideProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, decideProposal,
		arg.ID,
		arg.Status,
		arg.ResultID,
		arg.Anomalies,
		arg.Body,
	)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ConversationID,
		&i.VehicleID,
		&i.Operation,
		&i.Summary,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const deleteConsent = `-- name: DeleteConsent :exec
DELETE FROM assistant.consent WHERE account_id = $1
`

func (q *Queries) DeleteConsent(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConsent, accountID)
	return err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM assistant.conversation WHERE id = $1 AND account_id = $2
`

type DeleteConversationParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConsent = `-- name: GetConsent :one
SELECT account_id, provider, given_at FROM assistant.consent WHERE account_id = $1
`

func (q *Queries) GetConsent(ctx context.Context, accountID pgtype.UUID) (AssistantConsent, error) {
	row := q.db.QueryRow(ctx, getConsent, accountID)
	var i AssistantConsent
	err := row.Scan(&i.AccountID, &i.Provider, &i.GivenAt)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, account_id, vehicle_id, title, created_at, updated_at FROM assistant.conversation WHERE id = $1 AND account_id = $2
`

type GetConversationParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.AccountID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.VehicleID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT id, account_id, conversation_id, vehicle_id, operation, summary, body, anomalies, status, expires_at, result_id, created_at, decided_at FROM assistant.proposal WHERE id = $1 AND account_id = $2
`

type GetProposalParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, getProposal, arg.ID, arg.AccountID)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ConversationID,
		&i.VehicleID,
		&i.Operation,
		&i.Summary,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO assistant.conversation (id, account_id, vehicle_id, title) VALUES ($1, $2, $3, $4) RETURNING id, account_id, vehicle_id, title, created_at, updated_at
`

type InsertConversationParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	VehicleID pgtype.UUID
	Title     pgtype.Text
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRow(ctx, insertConversation,
		arg.ID,
		arg.AccountID,
		arg.VehicleID,
		arg.Title,
	)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.VehicleID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO assistant.message (id, conversation_id, role, text, proposal_ids) VALUES ($1, $2, $3, $4, $5) RETURNING id, conversation_id, role, text, proposal_ids, created_at
`

type InsertMessageParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Text           string
	ProposalIds    []pgtype.UUID
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (AssistantMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Text,
		arg.ProposalIds,
	)
	var i AssistantMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Text,
		&i.ProposalIds,
		&i.CreatedAt,
	)
	return i, err
}

const insertProposal = `-- name: InsertProposal :one
INSERT INTO assistant.proposal (id, account_id, conversation_id, vehicle_id, operation, summary, body, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8) RETURNING id, account_id, conversation_id, vehicle_id, operation, summary, body, anomalies, status, expires_at, result_id, created_at, decided_at
`

type InsertProposalParams struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	ConversationID pgtype.UUID
	VehicleID      pgtype.UUID
	Operation      string
	Summary        string
	Body           []byte
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, insertProposal,
		arg.ID,
		arg.AccountID,
		arg.ConversationID,
		arg.VehicleID,
		arg.Operation,
		arg.Summary,
		arg.Body,
		arg.ExpiresAt,
	)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ConversationID,
		&i.VehicleID,
		&i.Operation,
		&i.Summary,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertRequestLog = `-- name: InsertRequestLog :exec
INSERT INTO assistant.request_log (id, account_id, provider, model, input_tokens, output_tokens, tools) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertRequestLogParams struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	Provider     string
	Model        string
	InputTokens  int32
	OutputTokens int32
	Tools        []string
}

func (q *Queries) InsertRequestLog(ctx context.Context, arg InsertRequestLogParams) error {
	_, err := q.db.Exec(ctx, insertRequestLog,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Tools,
	)
	return err
}

const listConversations = `-- name: ListConversations :many
SELECT id, account_id, vehicle_id, title, created_at, updated_at FROM assistant.conversation WHERE account_id = $1 ORDER BY updated_at DESC LIMIT 50
`

func (q *Queries) ListConversations(ctx context.Context, accountID pgtype.UUID) ([]AssistantConversation, error) {
	rows, err := q.db.Query(ctx, listConversations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantConversation
	for rows.Next() {
		var i AssistantConversation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.VehicleID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, text, proposal_ids, created_at FROM assistant.message WHERE conversation_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]AssistantMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantMessage
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Text,
			&i.ProposalIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposals = `-- name: ListProposals :many
SELECT id, account_id, conversation_id, vehicle_id, operation, summary, body, anomalies, status, expires_at, result_id, created_at, decided_at FROM assistant.proposal WHERE id = ANY($2::uuid[]) AND account_id = $1
`

type ListProposalsParams struct {
	AccountID pgtype.UUID
	Ids       []pgtype.UUID
}

func (q *Queries) ListProposals(ctx context.Context, arg ListProposalsParams) ([]AssistantProposal, error) {
	rows, err := q.db.Query(ctx, listProposals, arg.AccountID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantProposal
	for rows.Next() {
		var i AssistantProposal
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ConversationID,
			&i.VehicleID,
			&i.Operation,
			&i.Summary,
			&i.Body,
			&i.Anomalies,
			&i.Status,
			&i.ExpiresAt,
			&i.ResultID,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProposal = `-- name: LockProposal :one
SELECT id, account_id, conversation_id, vehicle_id, operation, summary, body, anomalies, status, expires_at, result_id, created_at, decided_at FROM assistant.proposal WHERE id = $1 AND account_id = $2 FOR UPDATE
`

type LockProposalParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) LockProposal(ctx context.Context, arg LockProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, lockProposal, arg.ID, arg.AccountID)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ConversationID,
		&i.VehicleID,
		&i.Operation,
		&i.Summary,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const purgeOldConversations = `-- name: PurgeOldConversations :exec
DELETE FROM assistant.conversation WHERE account_id = $1 AND updated_at < $2
`

type PurgeOldConversationsParams struct {
	AccountID pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) PurgeOldConversations(ctx context.Context, arg PurgeOldConversationsParams) error {
	_, err := q.db.Exec(ctx, purgeOldConversations, arg.AccountID, arg.UpdatedAt)
	return err
}

const setProposalAnomalies = `-- name: SetProposalAnomalies :exec
UPDATE assistant.proposal SET anomalies = $2 WHERE id = $1
`

type SetProposalAnomaliesParams struct {
	ID        pgtype.UUID
	Anomalies []byte
}

func (q *Queries) SetProposalAnomalies(ctx context.Context, arg SetProposalAnomaliesParams) error {
	_, err := q.db.Exec(ctx, setProposalAnomalies, arg.ID, arg.Anomalies)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE assistant.conversation SET updated_at = now(), title = COALESCE(title, $2) WHERE id = $1
`

type TouchConversationParams struct {
	ID    pgtype.UUID
	Title pgtype.Text
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.ID, arg.Title)
	return err
}

const upsertConsent = `-- name: UpsertConsent :one
INSERT INTO assistant.consent (account_id, provider) VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE SET provider = EXCLUDED.provider, given_at = now()
RETURNING account_id, provider, given_at
`

type UpsertConsentParams struct {
	AccountID pgtype.UUID
	Provider  string
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) (AssistantConsent, error) {
	row := q.db.QueryRow(ctx, upsertConsent, arg.AccountID, arg.Provider)
	var i AssistantConsent
	err := row.Scan(&i.AccountID, &i.Provider, &i.GivenAt)
	return i, err
}
