// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assistant.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachProposals = `-- name: AttachProposals :exec
UPDATE assistant.proposal SET message_id = $1 WHERE id = ANY($2::uuid[])
`

type AttachProposalsParams struct {
	MessageID pgtype.UUID
	Ids       []pgtype.UUID
}

func (q *Queries) AttachProposals(ctx context.Context, arg AttachProposalsParams) error {
	_, err := q.db.Exec(ctx, attachProposals, arg.MessageID, arg.Ids)
	return err
}

const countRequestsSince = `-- name: CountRequestsSince :one
SELECT count(*) FROM assistant.request_log WHERE account_id = $1 AND occurred_at >= $2
`

type CountRequestsSinceParams struct {
	AccountID  pgtype.UUID
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) CountRequestsSince(ctx context.Context, arg CountRequestsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsSince, arg.AccountID, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideProposal = `-- name: DecideProposal :one
UPDATE assistant.proposal SET status = $2, result_id = $3, body = $4, decided_at = now() WHERE id = $1 AND status = 'pending' RETURNING id, conversation_id, message_id, account_id, vehicle_id, operation, body, anomalies, status, expires_at, result_id, created_at, decided_at
`

type DecideProposalParams struct {
	ID       pgtype.UUID
	Status   string
	ResultID pgtype.UUID
	Body     []byte
}

func (q *Queries) DecideProposal(ctx context.Context, arg DecideProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, decideProposal,
		arg.ID,
		arg.Status,
		arg.ResultID,
		arg.Body,
	)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.AccountID,
		&i.VehicleID,
		&i.Operation,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM assistant.conversation WHERE id = $1 AND account_id = $2
`

type DeleteConversationParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldConversations = `-- name: DeleteOldConversations :execrows
DELETE FROM assistant.conversation WHERE updated_at < $1
`

func (q *Queries) DeleteOldConversations(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldConversations, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversation = `-- name: GetConversation :one
SELECT id, account_id, vehicle_id, title, created_at, updated_at FROM assistant.conversation WHERE id = $1 AND account_id = $2
`

type GetConversationParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.AccountID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.VehicleID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT id, conversation_id, message_id, account_id, vehicle_id, operation, body, anomalies, status, expires_at, result_id, created_at, decided_at FROM assistant.proposal WHERE id = $1 AND account_id = $2
`

type GetProposalParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, getProposal, arg.ID, arg.AccountID)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.AccountID,
		&i.VehicleID,
		&i.Operation,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getUserState = `-- name: GetUserState :one
SELECT account_id, enabled, consent_provider, consent_at FROM assistant.user_state WHERE account_id = $1
`

func (q *Queries) GetUserState(ctx context.Context, accountID pgtype.UUID) (AssistantUserState, error) {
	row := q.db.QueryRow(ctx, getUserState, accountID)
	var i AssistantUserState
	err := row.Scan(
		&i.AccountID,
		&i.Enabled,
		&i.ConsentProvider,
		&i.ConsentAt,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO assistant.conversation (id, account_id, vehicle_id, title) VALUES ($1, $2, $3, $4) RETURNING id, account_id, vehicle_id, title, created_at, updated_at
`

type InsertConversationParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	VehicleID pgtype.UUID
	Title     pgtype.Text
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRow(ctx, insertConversation,
		arg.ID,
		arg.AccountID,
		arg.VehicleID,
		arg.Title,
	)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.VehicleID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO assistant.message (id, conversation_id, role, text, citations) VALUES ($1, $2, $3, $4, $5) RETURNING id, conversation_id, role, text, citations, created_at
`

type InsertMessageParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Text           string
	Citations      []byte
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (AssistantMessage, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Text,
		arg.Citations,
	)
	var i AssistantMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Text,
		&i.Citations,
		&i.CreatedAt,
	)
	return i, err
}

const insertProposal = `-- name: InsertProposal :one
INSERT INTO assistant.proposal (id, conversation_id, account_id, vehicle_id, operation, body, anomalies, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8) RETURNING id, conversation_id, message_id, account_id, vehicle_id, operation, body, anomalies, status, expires_at, result_id, created_at, decided_at
`

type InsertProposalParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	AccountID      pgtype.UUID
	VehicleID      pgtype.UUID
	Operation      string
	Body           []byte
	Anomalies      []byte
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRow(ctx, insertProposal,
		arg.ID,
		arg.ConversationID,
		arg.AccountID,
		arg.VehicleID,
		arg.Operation,
		arg.Body,
		arg.Anomalies,
		arg.ExpiresAt,
	)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.AccountID,
		&i.VehicleID,
		&i.Operation,
		&i.Body,
		&i.Anomalies,
		&i.Status,
		&i.ExpiresAt,
		&i.ResultID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertRequestLog = `-- name: InsertRequestLog :exec
INSERT INTO assistant.request_log (id, account_id, provider, model, input_tokens, output_tokens, tools, outcome)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRequestLogParams struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	Provider     string
	Model        string
	InputTokens  int64
	OutputTokens int64
	Tools        []string
	Outcome      string
}

func (q *Queries) InsertRequestLog(ctx context.Context, arg InsertRequestLogParams) error {
	_, err := q.db.Exec(ctx, insertRequestLog,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Tools,
		arg.Outcome,
	)
	return err
}

const listConversations = `-- name: ListConversations :many
SELECT id, account_id, vehicle_id, title, created_at, updated_at FROM assistant.conversation WHERE account_id = $1 ORDER BY updated_at DESC LIMIT 100
`

func (q *Queries) ListConversations(ctx context.Context, accountID pgtype.UUID) ([]AssistantConversation, error) {
	rows, err := q.db.Query(ctx, listConversations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantConversation
	for rows.Next() {
		var i AssistantConversation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.VehicleID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, text, citations, created_at FROM assistant.message WHERE conversation_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]AssistantMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantMessage
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Text,
			&i.Citations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalsForConversation = `-- name: ListProposalsForConversation :many
SELECT id, conversation_id, message_id, account_id, vehicle_id, operation, body, anomalies, status, expires_at, result_id, created_at, decided_at FROM assistant.proposal WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListProposalsForConversation(ctx context.Context, conversationID pgtype.UUID) ([]AssistantProposal, error) {
	rows, err := q.db.Query(ctx, listProposalsForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistantProposal
	for rows.Next() {
		var i AssistantProposal
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.AccountID,
			&i.VehicleID,
			&i.Operation,
			&i.Body,
			&i.Anomalies,
			&i.Status,
			&i.ExpiresAt,
			&i.ResultID,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE assistant.conversation SET updated_at = now(), title = COALESCE(title, $2) WHERE id = $1
`

type TouchConversationParams struct {
	ID    pgtype.UUID
	Title pgtype.Text
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.ID, arg.Title)
	return err
}

const upsertUserState = `-- name: UpsertUserState :exec
INSERT INTO assistant.user_state (account_id, enabled, consent_provider, consent_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id) DO UPDATE SET enabled = EXCLUDED.enabled, consent_provider = EXCLUDED.consent_provider, consent_at = EXCLUDED.consent_at
`

type UpsertUserStateParams struct {
	AccountID       pgtype.UUID
	Enabled         bool
	ConsentProvider pgtype.Text
	ConsentAt       pgtype.Timestamptz
}

func (q *Queries) UpsertUserState(ctx context.Context, arg UpsertUserStateParams) error {
	_, err := q.db.Exec(ctx, upsertUserState,
		arg.AccountID,
		arg.Enabled,
		arg.ConsentProvider,
		arg.ConsentAt,
	)
	return err
}
