// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trips.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureDefaultCategory = `-- name: EnsureDefaultCategory :exec
INSERT INTO trips.category (id, vehicle_id, name, kind, purpose_required, default_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (vehicle_id, default_key) DO NOTHING
`

type EnsureDefaultCategoryParams struct {
	ID              pgtype.UUID
	VehicleID       pgtype.UUID
	Name            string
	Kind            string
	PurposeRequired bool
	DefaultKey      pgtype.Text
	CreatedBy       pgtype.UUID
}

func (q *Queries) EnsureDefaultCategory(ctx context.Context, arg EnsureDefaultCategoryParams) error {
	_, err := q.db.Exec(ctx, ensureDefaultCategory,
		arg.ID,
		arg.VehicleID,
		arg.Name,
		arg.Kind,
		arg.PurposeRequired,
		arg.DefaultKey,
		arg.CreatedBy,
	)
	return err
}

const finishTrip = `-- name: FinishTrip :one
UPDATE trips.trip SET ended_at = $2, end_reading_id = $3, end_location = $4, note = $7, status = 'closed', updated_by = $5,
    updated_at = now(), version = version + 1
WHERE id = $1 AND version = $6 AND status = 'open'
RETURNING id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version
`

type FinishTripParams struct {
	ID           pgtype.UUID
	EndedAt      pgtype.Timestamptz
	EndReadingID pgtype.UUID
	EndLocation  pgtype.Text
	UpdatedBy    pgtype.UUID
	Version      int32
	Note         string
}

func (q *Queries) FinishTrip(ctx context.Context, arg FinishTripParams) (TripsTrip, error) {
	row := q.db.QueryRow(ctx, finishTrip,
		arg.ID,
		arg.EndedAt,
		arg.EndReadingID,
		arg.EndLocation,
		arg.UpdatedBy,
		arg.Version,
		arg.Note,
	)
	var i TripsTrip
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.VehicleID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TimeZone,
		&i.StartReadingID,
		&i.EndReadingID,
		&i.StartLocation,
		&i.EndLocation,
		&i.Purpose,
		&i.CategoryID,
		&i.DriverAccountID,
		&i.Note,
		&i.Status,
		&i.SupersedesID,
		&i.ChangeReason,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.Version,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, vehicle_id, name, kind, purpose_required, active, default_key, created_at, created_by, version FROM trips.category WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id pgtype.UUID) (TripsCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i TripsCategory
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Name,
		&i.Kind,
		&i.PurposeRequired,
		&i.Active,
		&i.DefaultKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getTrip = `-- name: GetTrip :one
SELECT id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version FROM trips.trip WHERE id = $1
`

func (q *Queries) GetTrip(ctx context.Context, id pgtype.UUID) (TripsTrip, error) {
	row := q.db.QueryRow(ctx, getTrip, id)
	var i TripsTrip
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.VehicleID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TimeZone,
		&i.StartReadingID,
		&i.EndReadingID,
		&i.StartLocation,
		&i.EndLocation,
		&i.Purpose,
		&i.CategoryID,
		&i.DriverAccountID,
		&i.Note,
		&i.Status,
		&i.SupersedesID,
		&i.ChangeReason,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.Version,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO trips.category (id, vehicle_id, name, kind, purpose_required, active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, vehicle_id, name, kind, purpose_required, active, default_key, created_at, created_by, version
`

type InsertCategoryParams struct {
	ID              pgtype.UUID
	VehicleID       pgtype.UUID
	Name            string
	Kind            string
	PurposeRequired bool
	Active          bool
	CreatedBy       pgtype.UUID
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (TripsCategory, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.ID,
		arg.VehicleID,
		arg.Name,
		arg.Kind,
		arg.PurposeRequired,
		arg.Active,
		arg.CreatedBy,
	)
	var i TripsCategory
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Name,
		&i.Kind,
		&i.PurposeRequired,
		&i.Active,
		&i.DefaultKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const insertTrip = `-- name: InsertTrip :one
INSERT INTO trips.trip (id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location,
    end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $19)
RETURNING id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version
`

type InsertTripParams struct {
	ID              pgtype.UUID
	RootID          pgtype.UUID
	VehicleID       pgtype.UUID
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	TimeZone        string
	StartReadingID  pgtype.UUID
	EndReadingID    pgtype.UUID
	StartLocation   pgtype.Text
	EndLocation     pgtype.Text
	Purpose         pgtype.Text
	CategoryID      pgtype.UUID
	DriverAccountID pgtype.UUID
	Note            string
	Status          string
	SupersedesID    pgtype.UUID
	ChangeReason    pgtype.Text
	Origin          string
	CreatedBy       pgtype.UUID
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) (TripsTrip, error) {
	row := q.db.QueryRow(ctx, insertTrip,
		arg.ID,
		arg.RootID,
		arg.VehicleID,
		arg.StartedAt,
		arg.EndedAt,
		arg.TimeZone,
		arg.StartReadingID,
		arg.EndReadingID,
		arg.StartLocation,
		arg.EndLocation,
		arg.Purpose,
		arg.CategoryID,
		arg.DriverAccountID,
		arg.Note,
		arg.Status,
		arg.SupersedesID,
		arg.ChangeReason,
		arg.Origin,
		arg.CreatedBy,
	)
	var i TripsTrip
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.VehicleID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TimeZone,
		&i.StartReadingID,
		&i.EndReadingID,
		&i.StartLocation,
		&i.EndLocation,
		&i.Purpose,
		&i.CategoryID,
		&i.DriverAccountID,
		&i.Note,
		&i.Status,
		&i.SupersedesID,
		&i.ChangeReason,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.Version,
	)
	return i, err
}

const insertTripPhoto = `-- name: InsertTripPhoto :exec
INSERT INTO documents.attachment (id, vehicle_id, file_id, target_type, target_id, role, created_by)
VALUES ($1, $2, $3, 'trip', $4, $5, $6)
`

type InsertTripPhotoParams struct {
	ID        pgtype.UUID
	VehicleID pgtype.UUID
	FileID    pgtype.UUID
	TargetID  pgtype.UUID
	Role      string
	CreatedBy pgtype.UUID
}

func (q *Queries) InsertTripPhoto(ctx context.Context, arg InsertTripPhotoParams) error {
	_, err := q.db.Exec(ctx, insertTripPhoto,
		arg.ID,
		arg.VehicleID,
		arg.FileID,
		arg.TargetID,
		arg.Role,
		arg.CreatedBy,
	)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, vehicle_id, name, kind, purpose_required, active, default_key, created_at, created_by, version FROM trips.category WHERE vehicle_id = $1 ORDER BY default_key IS NULL, array_position(ARRAY['private','business','commute','other']::text[], default_key), name, id
`

func (q *Queries) ListCategories(ctx context.Context, vehicleID pgtype.UUID) ([]TripsCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripsCategory
	for rows.Next() {
		var i TripsCategory
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Name,
			&i.Kind,
			&i.PurposeRequired,
			&i.Active,
			&i.DefaultKey,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripPhotos = `-- name: ListTripPhotos :many
SELECT target_id, role, file_id FROM documents.attachment
WHERE target_type = 'trip' AND target_id = ANY($1::uuid[]) AND role IN ('tacho_start', 'tacho_end')
  AND deleted_at IS NULL AND file_id IS NOT NULL
ORDER BY created_at
`

type ListTripPhotosRow struct {
	TargetID pgtype.UUID
	Role     string
	FileID   pgtype.UUID
}

func (q *Queries) ListTripPhotos(ctx context.Context, rootIds []pgtype.UUID) ([]ListTripPhotosRow, error) {
	rows, err := q.db.Query(ctx, listTripPhotos, rootIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripPhotosRow
	for rows.Next() {
		var i ListTripPhotosRow
		if err := rows.Scan(&i.TargetID, &i.Role, &i.FileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version FROM trips.trip
WHERE vehicle_id = $1
  AND ($2::boolean OR status IN ('open', 'closed'))
  AND ($3::timestamptz IS NULL OR started_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR started_at < $4::timestamptz)
  AND ($5::timestamptz IS NULL OR (started_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY started_at DESC, id DESC
LIMIT $7
`

type ListTripsParams struct {
	VehicleID      pgtype.UUID
	IncludeHistory bool
	FromTs         pgtype.Timestamptz
	ToTs           pgtype.Timestamptz
	BeforeTs       pgtype.Timestamptz
	BeforeID       pgtype.UUID
	Lim            int32
}

func (q *Queries) ListTrips(ctx context.Context, arg ListTripsParams) ([]TripsTrip, error) {
	rows, err := q.db.Query(ctx, listTrips,
		arg.VehicleID,
		arg.IncludeHistory,
		arg.FromTs,
		arg.ToTs,
		arg.BeforeTs,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripsTrip
	for rows.Next() {
		var i TripsTrip
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.VehicleID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TimeZone,
			&i.StartReadingID,
			&i.EndReadingID,
			&i.StartLocation,
			&i.EndLocation,
			&i.Purpose,
			&i.CategoryID,
			&i.DriverAccountID,
			&i.Note,
			&i.Status,
			&i.SupersedesID,
			&i.ChangeReason,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTripPhoto = `-- name: ReplaceTripPhoto :exec
UPDATE documents.attachment SET deleted_at = now()
WHERE target_type = 'trip' AND target_id = $1 AND role = $2 AND deleted_at IS NULL
`

type ReplaceTripPhotoParams struct {
	TargetID pgtype.UUID
	Role     string
}

func (q *Queries) ReplaceTripPhoto(ctx context.Context, arg ReplaceTripPhotoParams) error {
	_, err := q.db.Exec(ctx, replaceTripPhoto, arg.TargetID, arg.Role)
	return err
}

const setTripStatus = `-- name: SetTripStatus :one
UPDATE trips.trip SET status = $2, change_reason = COALESCE($5, change_reason), updated_by = $3,
    updated_at = now(), version = version + 1
WHERE id = $1 AND version = $4 AND status IN ('open', 'closed')
RETURNING id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version
`

type SetTripStatusParams struct {
	ID           pgtype.UUID
	Status       string
	UpdatedBy    pgtype.UUID
	Version      int32
	ChangeReason pgtype.Text
}

func (q *Queries) SetTripStatus(ctx context.Context, arg SetTripStatusParams) (TripsTrip, error) {
	row := q.db.QueryRow(ctx, setTripStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedBy,
		arg.Version,
		arg.ChangeReason,
	)
	var i TripsTrip
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.VehicleID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TimeZone,
		&i.StartReadingID,
		&i.EndReadingID,
		&i.StartLocation,
		&i.EndLocation,
		&i.Purpose,
		&i.CategoryID,
		&i.DriverAccountID,
		&i.Note,
		&i.Status,
		&i.SupersedesID,
		&i.ChangeReason,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.Version,
	)
	return i, err
}

const tripHistory = `-- name: TripHistory :many
SELECT id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version FROM trips.trip WHERE root_id = $1 ORDER BY created_at, id
`

func (q *Queries) TripHistory(ctx context.Context, rootID pgtype.UUID) ([]TripsTrip, error) {
	rows, err := q.db.Query(ctx, tripHistory, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripsTrip
	for rows.Next() {
		var i TripsTrip
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.VehicleID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TimeZone,
			&i.StartReadingID,
			&i.EndReadingID,
			&i.StartLocation,
			&i.EndLocation,
			&i.Purpose,
			&i.CategoryID,
			&i.DriverAccountID,
			&i.Note,
			&i.Status,
			&i.SupersedesID,
			&i.ChangeReason,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tripPhotoFile = `-- name: TripPhotoFile :one

SELECT id, vehicle_id, media_type, derivatives, deleted_at FROM documents.file WHERE id = $1
`

type TripPhotoFileRow struct {
	ID          pgtype.UUID
	VehicleID   pgtype.UUID
	MediaType   string
	Derivatives []string
	DeletedAt   pgtype.Timestamptz
}

// Tachofotos (Start/Ende) hängen als Verknüpfung an der ersten Fassung (root_id), damit Korrekturen sie behalten.
func (q *Queries) TripPhotoFile(ctx context.Context, id pgtype.UUID) (TripPhotoFileRow, error) {
	row := q.db.QueryRow(ctx, tripPhotoFile, id)
	var i TripPhotoFileRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MediaType,
		&i.Derivatives,
		&i.DeletedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE trips.category SET name = $2, kind = $3, purpose_required = $4, active = $5, version = version + 1
WHERE id = $1 AND version = $6
RETURNING id, vehicle_id, name, kind, purpose_required, active, default_key, created_at, created_by, version
`

type UpdateCategoryParams struct {
	ID              pgtype.UUID
	Name            string
	Kind            string
	PurposeRequired bool
	Active          bool
	Version         int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (TripsCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.PurposeRequired,
		arg.Active,
		arg.Version,
	)
	var i TripsCategory
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Name,
		&i.Kind,
		&i.PurposeRequired,
		&i.Active,
		&i.DefaultKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const updateOpenTrip = `-- name: UpdateOpenTrip :one
UPDATE trips.trip SET started_at = $2, start_reading_id = $3, start_location = $4, purpose = $5, category_id = $6,
    driver_account_id = $7, note = $8, updated_by = $9, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $10 AND status = 'open'
RETURNING id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version
`

type UpdateOpenTripParams struct {
	ID              pgtype.UUID
	StartedAt       pgtype.Timestamptz
	StartReadingID  pgtype.UUID
	StartLocation   pgtype.Text
	Purpose         pgtype.Text
	CategoryID      pgtype.UUID
	DriverAccountID pgtype.UUID
	Note            string
	UpdatedBy       pgtype.UUID
	Version         int32
}

func (q *Queries) UpdateOpenTrip(ctx context.Context, arg UpdateOpenTripParams) (TripsTrip, error) {
	row := q.db.QueryRow(ctx, updateOpenTrip,
		arg.ID,
		arg.StartedAt,
		arg.StartReadingID,
		arg.StartLocation,
		arg.Purpose,
		arg.CategoryID,
		arg.DriverAccountID,
		arg.Note,
		arg.UpdatedBy,
		arg.Version,
	)
	var i TripsTrip
	err := row.Scan(
		&i.ID,
		&i.RootID,
		&i.VehicleID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TimeZone,
		&i.StartReadingID,
		&i.EndReadingID,
		&i.StartLocation,
		&i.EndLocation,
		&i.Purpose,
		&i.CategoryID,
		&i.DriverAccountID,
		&i.Note,
		&i.Status,
		&i.SupersedesID,
		&i.ChangeReason,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.Version,
	)
	return i, err
}

const validTrips = `-- name: ValidTrips :many
SELECT id, root_id, vehicle_id, started_at, ended_at, time_zone, start_reading_id, end_reading_id, start_location, end_location, purpose, category_id, driver_account_id, note, status, supersedes_id, change_reason, origin, created_at, created_by, updated_at, updated_by, recorded_at, version FROM trips.trip WHERE vehicle_id = $1 AND status IN ('open', 'closed') ORDER BY started_at, id
`

func (q *Queries) ValidTrips(ctx context.Context, vehicleID pgtype.UUID) ([]TripsTrip, error) {
	rows, err := q.db.Query(ctx, validTrips, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripsTrip
	for rows.Next() {
		var i TripsTrip
		if err := rows.Scan(
			&i.ID,
			&i.RootID,
			&i.VehicleID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TimeZone,
			&i.StartReadingID,
			&i.EndReadingID,
			&i.StartLocation,
			&i.EndLocation,
			&i.Purpose,
			&i.CategoryID,
			&i.DriverAccountID,
			&i.Note,
			&i.Status,
			&i.SupersedesID,
			&i.ChangeReason,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
