// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fuel.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFill = `-- name: GetFill :one
SELECT id, vehicle_id, occurred_at, time_zone, time_precision, energy_carrier, quantity, input_quantity, input_unit, fill_level, previous_missed, odometer_reading_id, cost_amount_minor, cost_currency, input_price_per_unit, input_price_currency, input_price_unit, soc_start_pct, soc_end_pct, charge_type, station, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM fuel.fill WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFill(ctx context.Context, id pgtype.UUID) (FuelFill, error) {
	row := q.db.QueryRow(ctx, getFill, id)
	var i FuelFill
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.EnergyCarrier,
		&i.Quantity,
		&i.InputQuantity,
		&i.InputUnit,
		&i.FillLevel,
		&i.PreviousMissed,
		&i.OdometerReadingID,
		&i.CostAmountMinor,
		&i.CostCurrency,
		&i.InputPricePerUnit,
		&i.InputPriceCurrency,
		&i.InputPriceUnit,
		&i.SocStartPct,
		&i.SocEndPct,
		&i.ChargeType,
		&i.Station,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getFillAny = `-- name: GetFillAny :one
SELECT id, vehicle_id, occurred_at, time_zone, time_precision, energy_carrier, quantity, input_quantity, input_unit, fill_level, previous_missed, odometer_reading_id, cost_amount_minor, cost_currency, input_price_per_unit, input_price_currency, input_price_unit, soc_start_pct, soc_end_pct, charge_type, station, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM fuel.fill WHERE id = $1
`

func (q *Queries) GetFillAny(ctx context.Context, id pgtype.UUID) (FuelFill, error) {
	row := q.db.QueryRow(ctx, getFillAny, id)
	var i FuelFill
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.EnergyCarrier,
		&i.Quantity,
		&i.InputQuantity,
		&i.InputUnit,
		&i.FillLevel,
		&i.PreviousMissed,
		&i.OdometerReadingID,
		&i.CostAmountMinor,
		&i.CostCurrency,
		&i.InputPricePerUnit,
		&i.InputPriceCurrency,
		&i.InputPriceUnit,
		&i.SocStartPct,
		&i.SocEndPct,
		&i.ChargeType,
		&i.Station,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertFill = `-- name: InsertFill :one
INSERT INTO fuel.fill (id, vehicle_id, occurred_at, time_zone, time_precision, energy_carrier, quantity, input_quantity, input_unit,
    fill_level, previous_missed, odometer_reading_id, cost_amount_minor, cost_currency, input_price_per_unit, input_price_currency,
    input_price_unit, soc_start_pct, soc_end_pct, charge_type, station, note, tags, confirmed_anomalies, origin, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $26)
RETURNING id, vehicle_id, occurred_at, time_zone, time_precision, energy_carrier, quantity, input_quantity, input_unit, fill_level, previous_missed, odometer_reading_id, cost_amount_minor, cost_currency, input_price_per_unit, input_price_currency, input_price_unit, soc_start_pct, soc_end_pct, charge_type, station, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type InsertFillParams struct {
	ID                 pgtype.UUID
	VehicleID          pgtype.UUID
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	EnergyCarrier      string
	Quantity           int64
	InputQuantity      pgtype.Numeric
	InputUnit          string
	FillLevel          string
	PreviousMissed     bool
	OdometerReadingID  pgtype.UUID
	CostAmountMinor    pgtype.Int8
	CostCurrency       pgtype.Text
	InputPricePerUnit  pgtype.Numeric
	InputPriceCurrency pgtype.Text
	InputPriceUnit     pgtype.Text
	SocStartPct        pgtype.Numeric
	SocEndPct          pgtype.Numeric
	ChargeType         pgtype.Text
	Station            pgtype.Text
	Note               string
	Tags               []string
	ConfirmedAnomalies []byte
	Origin             string
	CreatedBy          pgtype.UUID
}

func (q *Queries) InsertFill(ctx context.Context, arg InsertFillParams) (FuelFill, error) {
	row := q.db.QueryRow(ctx, insertFill,
		arg.ID,
		arg.VehicleID,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.EnergyCarrier,
		arg.Quantity,
		arg.InputQuantity,
		arg.InputUnit,
		arg.FillLevel,
		arg.PreviousMissed,
		arg.OdometerReadingID,
		arg.CostAmountMinor,
		arg.CostCurrency,
		arg.InputPricePerUnit,
		arg.InputPriceCurrency,
		arg.InputPriceUnit,
		arg.SocStartPct,
		arg.SocEndPct,
		arg.ChargeType,
		arg.Station,
		arg.Note,
		arg.Tags,
		arg.ConfirmedAnomalies,
		arg.Origin,
		arg.CreatedBy,
	)
	var i FuelFill
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.EnergyCarrier,
		&i.Quantity,
		&i.InputQuantity,
		&i.InputUnit,
		&i.FillLevel,
		&i.PreviousMissed,
		&i.OdometerReadingID,
		&i.CostAmountMinor,
		&i.CostCurrency,
		&i.InputPricePerUnit,
		&i.InputPriceCurrency,
		&i.InputPriceUnit,
		&i.SocStartPct,
		&i.SocEndPct,
		&i.ChargeType,
		&i.Station,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listFills = `-- name: ListFills :many
SELECT id, vehicle_id, occurred_at, time_zone, time_precision, energy_carrier, quantity, input_quantity, input_unit, fill_level, previous_missed, odometer_reading_id, cost_amount_minor, cost_currency, input_price_per_unit, input_price_currency, input_price_unit, soc_start_pct, soc_end_pct, charge_type, station, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version FROM fuel.fill
WHERE vehicle_id = $1 AND ($2::boolean OR deleted_at IS NULL)
ORDER BY occurred_at, recorded_at, id
`

type ListFillsParams struct {
	VehicleID      pgtype.UUID
	IncludeDeleted bool
}

func (q *Queries) ListFills(ctx context.Context, arg ListFillsParams) ([]FuelFill, error) {
	rows, err := q.db.Query(ctx, listFills, arg.VehicleID, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuelFill
	for rows.Next() {
		var i FuelFill
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.OccurredAt,
			&i.TimeZone,
			&i.TimePrecision,
			&i.EnergyCarrier,
			&i.Quantity,
			&i.InputQuantity,
			&i.InputUnit,
			&i.FillLevel,
			&i.PreviousMissed,
			&i.OdometerReadingID,
			&i.CostAmountMinor,
			&i.CostCurrency,
			&i.InputPricePerUnit,
			&i.InputPriceCurrency,
			&i.InputPriceUnit,
			&i.SocStartPct,
			&i.SocEndPct,
			&i.ChargeType,
			&i.Station,
			&i.Note,
			&i.Tags,
			&i.ConfirmedAnomalies,
			&i.Origin,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.RecordedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFill = `-- name: SoftDeleteFill :execrows
UPDATE fuel.fill SET deleted_at = now(), updated_by = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteFillParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
	Version   int32
}

func (q *Queries) SoftDeleteFill(ctx context.Context, arg SoftDeleteFillParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFill, arg.ID, arg.UpdatedBy, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFill = `-- name: UpdateFill :one
UPDATE fuel.fill SET occurred_at = $2, time_zone = $3, time_precision = $4, energy_carrier = $5, quantity = $6, input_quantity = $7,
    input_unit = $8, fill_level = $9, previous_missed = $10, odometer_reading_id = $11, cost_amount_minor = $12, cost_currency = $13,
    input_price_per_unit = $14, input_price_currency = $15, input_price_unit = $16, soc_start_pct = $17, soc_end_pct = $18,
    charge_type = $19, station = $20, note = $21, tags = $22, confirmed_anomalies = $23, updated_by = $24,
    updated_at = now(), version = version + 1
WHERE id = $1 AND version = $25 AND deleted_at IS NULL
RETURNING id, vehicle_id, occurred_at, time_zone, time_precision, energy_carrier, quantity, input_quantity, input_unit, fill_level, previous_missed, odometer_reading_id, cost_amount_minor, cost_currency, input_price_per_unit, input_price_currency, input_price_unit, soc_start_pct, soc_end_pct, charge_type, station, note, tags, confirmed_anomalies, origin, created_at, created_by, updated_at, updated_by, recorded_at, deleted_at, version
`

type UpdateFillParams struct {
	ID                 pgtype.UUID
	OccurredAt         pgtype.Timestamptz
	TimeZone           string
	TimePrecision      string
	EnergyCarrier      string
	Quantity           int64
	InputQuantity      pgtype.Numeric
	InputUnit          string
	FillLevel          string
	PreviousMissed     bool
	OdometerReadingID  pgtype.UUID
	CostAmountMinor    pgtype.Int8
	CostCurrency       pgtype.Text
	InputPricePerUnit  pgtype.Numeric
	InputPriceCurrency pgtype.Text
	InputPriceUnit     pgtype.Text
	SocStartPct        pgtype.Numeric
	SocEndPct          pgtype.Numeric
	ChargeType         pgtype.Text
	Station            pgtype.Text
	Note               string
	Tags               []string
	ConfirmedAnomalies []byte
	UpdatedBy          pgtype.UUID
	Version            int32
}

func (q *Queries) UpdateFill(ctx context.Context, arg UpdateFillParams) (FuelFill, error) {
	row := q.db.QueryRow(ctx, updateFill,
		arg.ID,
		arg.OccurredAt,
		arg.TimeZone,
		arg.TimePrecision,
		arg.EnergyCarrier,
		arg.Quantity,
		arg.InputQuantity,
		arg.InputUnit,
		arg.FillLevel,
		arg.PreviousMissed,
		arg.OdometerReadingID,
		arg.CostAmountMinor,
		arg.CostCurrency,
		arg.InputPricePerUnit,
		arg.InputPriceCurrency,
		arg.InputPriceUnit,
		arg.SocStartPct,
		arg.SocEndPct,
		arg.ChargeType,
		arg.Station,
		arg.Note,
		arg.Tags,
		arg.ConfirmedAnomalies,
		arg.UpdatedBy,
		arg.Version,
	)
	var i FuelFill
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredAt,
		&i.TimeZone,
		&i.TimePrecision,
		&i.EnergyCarrier,
		&i.Quantity,
		&i.InputQuantity,
		&i.InputUnit,
		&i.FillLevel,
		&i.PreviousMissed,
		&i.OdometerReadingID,
		&i.CostAmountMinor,
		&i.CostCurrency,
		&i.InputPricePerUnit,
		&i.InputPriceCurrency,
		&i.InputPriceUnit,
		&i.SocStartPct,
		&i.SocEndPct,
		&i.ChargeType,
		&i.Station,
		&i.Note,
		&i.Tags,
		&i.ConfirmedAnomalies,
		&i.Origin,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.RecordedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
