// Command genstubs erzeugt aus dem generierten StrictServerInterface eine
// Implementierung, die für jede Operation ErrNotImplemented liefert. Der Server
// bettet sie ein und überschreibt nur die umgesetzten Operationen.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
)

func main() {
	in := flag.String("in", "api.gen.go", "generierte API-Datei")
	out := flag.String("out", "stubs.gen.go", "Zieldatei")
	flag.Parse()

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, *in, nil, 0)
	if err != nil {
		log.Fatal(err)
	}
	var names []string
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "StrictServerInterface" {
			return true
		}
		for _, m := range ts.Type.(*ast.InterfaceType).Methods.List {
			names = append(names, m.Names[0].Name)
		}
		return false
	})
	if len(names) == 0 {
		log.Fatal("StrictServerInterface nicht gefunden")
	}
	sort.Strings(names)
	var b bytes.Buffer
	b.WriteString("// Code generated by genstubs. DO NOT EDIT.\n\npackage api\n\nimport \"context\"\n\n")
	b.WriteString("// NotImplemented (strict) beantwortet jede Operation mit ErrNotImplemented.\ntype NotImplemented struct{}\n\n")
	b.WriteString("var _ StrictServerInterface = NotImplemented{}\n\n")
	for _, n := range names {
		fmt.Fprintf(&b, "func (NotImplemented) %s(context.Context, %sRequestObject) (%sResponseObject, error) {\n\treturn nil, ErrNotImplemented\n}\n\n", n, n, n)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}
